// Interface controls, hazards and livestock: 12x12 pixel art, one string per row, letters index the palette.
export const controlsAndHazardSprites = {
  drought: [
    '........y...',
    '...G...yyy..',
    '.G.G....y...',
    '.GGG........',
    '...G..yyy...',
    '.yyyyyyyyyy.',
    '..sss.ssss..',
  ],
  germ: [
    '..g..g..g...',
    '...ggggg....',
    '..gGggGgg...',
    '.ggggggggg..',
    '..ggGgggg...',
    '...ggggg....',
    '..g..g..g...',
  ],
  clock: [
    '....yyy.....',
    '.....y......',
    '...wwwww....',
    '..wwwwwBw...',
    '.wwwwwBwww..',
    '.wwwwwBBww..',
    '.wwwwwwwww..',
    '..wwwwwww...',
    '...sssss....',
  ],
  pause: [
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
  ],
  play: [
    '...y........',
    '...yyy......',
    '...yyyyy....',
    '...yyyyyyy..',
    '...yyyyy....',
    '...yyy......',
    '...y........',
  ],
  fast: [
    '.y....y.....',
    '.yy...yy....',
    '.yyy..yyy...',
    '.yyyy.yyyy..',
    '.yyy..yyy...',
    '.yy...yy....',
    '.y....y.....',
  ],
  bolt: [
    '.....yyyy...',
    '....yyyy....',
    '...yyyy.....',
    '..yyyyyyy...',
    '.....yyy....',
    '....yyy.....',
    '...yy.......',
    '..y.........',
  ],
  turtle: ['...GGGGG....', '..GgGgGgG...', '..GGgGgGGgg.', '.gGgGgGgGgo.', '..GGGGGGG...', '..g.....g...'],
  chart: [
    '.........yy.',
    '.........yy.',
    '......gg.yy.',
    '......gg.yy.',
    '...rr.gg.yy.',
    '...rr.gg.yy.',
    '...rr.gg.yy.',
    '.ssssssssss.',
  ],
  book: [
    '..RRRRRRRR..',
    '..RRwwwwwR..',
    '..RRwssswR..',
    '..RRwwwwwR..',
    '..RRwssswR..',
    '..RRwwwwwR..',
    '..RRwwwwwR..',
    '..RRyyyyyR..',
    '..RRRRRRRR..',
  ],
  gear: [
    '.....ss.....',
    '..s.ssss.s..',
    '..ssssssss..',
    '...ss..ss...',
    '.sss....sss.',
    '.sss....sss.',
    '...ss..ss...',
    '..ssssssss..',
    '..s.ssss.s..',
    '.....ss.....',
  ],
  dots: ['.ww..ww..ww.', '.ww..ww..ww.'],
  crown: ['.y...y...y..', '.yy.yyy.yy..', '.yyyyyyyyy..', '.yryybyyry..', '.yyyyyyyyy..', '.RRRRRRRRR..'],
  moon: [
    '...wwww.....',
    '..www.......',
    '.www........',
    '.ww.........',
    '.ww.........',
    '.www........',
    '..www.......',
    '...wwww.....',
  ],
  expand: [
    '.www....www.',
    '.w........w.',
    '.w........w.',
    '............',
    '............',
    '.w........w.',
    '.w........w.',
    '.www....www.',
  ],
  panelLeft: [
    '.ssssssssss.',
    '.syys.....s.',
    '.syys.....s.',
    '.syys.....s.',
    '.syys.....s.',
    '.syys.....s.',
    '.syys.....s.',
    '.ssssssssss.',
  ],
  panelRight: [
    '.ssssssssss.',
    '.s.....syys.',
    '.s.....syys.',
    '.s.....syys.',
    '.s.....syys.',
    '.s.....syys.',
    '.s.....syys.',
    '.ssssssssss.',
  ],
  bloom: [
    '.....g......',
    '..g.ggg.g...',
    '..ggyyygg...',
    '.gyybbbyyg..',
    'ggybbbbbygg.',
    '.gyybbbyyg..',
    '..ggyyygg...',
    '..g.ggg.g...',
    '.....g......',
  ],
  poison: [
    '....ss......',
    '....ww......',
    '....ww......',
    '...wggw.....',
    '..wgGggw....',
    '.wggoogGw...',
    '.wgGoogGw...',
    '.wggGggGw...',
    '..wwwwww....',
  ],
  meteor: [
    '.........yy.',
    '........yy..',
    '.......yy...',
    '....rry.....',
    '...rRRrr....',
    '..rRssRr....',
    '..rRssRr....',
    '...rRRr.....',
    '....rr......',
  ],
  sparkle: [
    '.....y......',
    '.....y......',
    '..y.yyy.y...',
    '...yywyy....',
    'yyyywwwyyyy.',
    '...yywyy....',
    '..y.yyy.y...',
    '.....y......',
    '.....y......',
  ],
  bulb: [
    '....yyy.....',
    '...yywyy....',
    '..yywyyyy...',
    '..yyyyyyy...',
    '..yyyyyyy...',
    '...yyyyy....',
    '....sss.....',
    '....sss.....',
    '.....s......',
  ],
  dove: [
    '........ww..',
    '.......wwow.',
    '.ww...wwwwy.',
    'wwwww.www...',
    '.wwwwwwww...',
    '..wwwwwww...',
    '....wwww....',
    '.....s.s....',
  ],
  quake: [
    '..ss........',
    '..sss....ss.',
    '...ss...sss.',
    '....ss.sss..',
    '.....sss....',
    '....ss.ss...',
    '...ss...ss..',
    'ggsgggggsgg.',
    'GGGGGGGGGGG.',
  ],
  bear: [
    '.........RR.',
    '..RRRRRRRRR.',
    '.RRRRRRRRRso',
    '.RRRRRRRRRss',
    '.RRRRRRRRRR.',
    '..RRRRRRRR..',
    '..RR.RR.RR..',
    '..RR....RR..',
  ],
  sheep: [
    '..swwswws...',
    '.wwwwwwwwoo.',
    'swwwwwwwwowo',
    'wwwwwwwwwoo.',
    '.wswwwsww...',
    '..o..o.o....',
    '..o..o.o....',
  ],
  cow: [
    '.........s.s',
    '.wwwwwwwwooo',
    'wooowwwowooo',
    'wooowwwwwppp',
    'wwwwwoowww..',
    '.wwwwoowww..',
    '.o..o..o.o..',
    '.o..o..o.o..',
  ],
} satisfies Record<string, string[]>
