// Monsters, biome and world markers: 12x12 pixel art, one string per row, letters index the palette.
export const creatureAndMarkerSprites = {
  blizzard: [
    '...www......',
    '..wwwww.ww..',
    '.wwwwwwwwww.',
    '.ssssssssss.',
    '..w...w...w.',
    '.www.www.www',
    '..w...w...w.',
    '....w...w...',
    '...www.www..',
    '....w...w...',
  ],
  zombie: [
    '..gggg......',
    '..gogg......',
    '..gggg......',
    '...gg.......',
    '..BBBBggggg.',
    '..BBBB......',
    '..BBBB......',
    '..ss.ss.....',
    '..ss.ss.....',
    '..oo.oo.....',
  ],
  demon: [
    '.r......r...',
    '.rr....rr...',
    '..rrrrrr....',
    '..ryrryr....',
    '..rrrrrr....',
    '..rwwwwr....',
    '...rrrr.....',
    '..RRRRRR....',
    '.R.RRRR.R...',
    '...R..R.....',
  ],
  dragon: [
    '..........G.',
    '.G.......GGo',
    'GGG.....GGGG',
    '.GGGG..GGG..',
    '..GGGGGGG...',
    '...GgggGG...',
    '..GGGGGGGG..',
    '.G...GG..G..',
    '....G..G....',
  ],
  alien: [
    '...gggggg...',
    '..gggggggg..',
    '..googgoog..',
    '..googgoog..',
    '...gggggg...',
    '....gggg....',
    '.....gg.....',
    '...ssssss...',
    '..s.ssss.s..',
    '....s..s....',
  ],
  ufo: [
    '.....bb.....',
    '....bwwb....',
    '...bbbbbb...',
    '.ssssssssss.',
    'ssyssyssyss.',
    '.ssssssssss.',
    '...y....y...',
    '..y......y..',
  ],
  b_meadow: [
    '............',
    '..p.....y...',
    '.pyp...yry..',
    '..p.y...y...',
    '..g.g.g.g.g.',
    '.ggGggGgggg.',
    'GgGgGgGgGgGG',
    'GGGGGGGGGGGG',
  ],
  b_oak: [
    '....gggg....',
    '..gggGgggg..',
    '.ggGgggGggg.',
    '.gggggGgggg.',
    '..ggGgggGg..',
    '...gggggg...',
    '.....ss.....',
    '.....ss.....',
    '....ssss....',
  ],
  b_palm: [
    '..gg....gg..',
    '.ggGg..gGgg.',
    'g...gggg...g',
    '....gGGg....',
    '.....ss.....',
    '.....s......',
    '......s.....',
    '......s.....',
    '.....sss....',
  ],
  b_acacia: [
    '..GGGGGGGG..',
    '.GgggggggggG',
    '..GGGGGGGG..',
    '.....s......',
    '......s.....',
    '....s.s.....',
    '.....s......',
    '.....s......',
    '....sss.....',
  ],
  b_cactus: [
    '.....g......',
    '.....gG.....',
    '.g...gG.....',
    '.gG..gG..g..',
    '.gGggGG..gG.',
    '..GGggG.ggG.',
    '.....gGGG...',
    '.....gG.....',
    '.yyyyyyyyyy.',
  ],
  b_mesa: [
    '............',
    '...RRRRR....',
    '...rrrrR....',
    '...rrrrR....',
    '..rrrrrrR...',
    '..rrrrrrRR..',
    '.rrrrrrrrRR.',
    'yyyyyyyyyyyy',
  ],
  b_reeds: [
    '..s....s....',
    '..s.s..s.s..',
    '.gs.s.gs.s..',
    '.g.gs.g..sg.',
    '.g.g..g.g.g.',
    'bbgbgbbgbgbb',
    'bbbbbbbbbbbb',
  ],
  b_tundra: [
    '............',
    '.....ww.....',
    '...wwwwww...',
    '..wsswwwsw..',
    '.wwwwwwwwww.',
    'wwsswwwwssww',
    'wwwwwwwwwwww',
  ],
  b_pine: [
    '.....w......',
    '....wGw.....',
    '...wGGGw....',
    '....GGG.....',
    '..wGGGGGw...',
    '...GGGGG....',
    '.wGGGGGGGw..',
    '.....s......',
    '.....s......',
  ],
  b_hearts: [
    '.rr.rr......',
    'rrrrrrr.....',
    'rrrrrrr.rr.r',
    '.rrrrrrrrrrr',
    '..rrrr.rrrrr',
    '...rr...rrr.',
    '.........r..',
  ],
  b_dog: [
    '.........ss.',
    '........ssso',
    '.sssssssssss',
    'ssssssssss..',
    '.ssssssss...',
    '.s.s...s.s..',
    '.s.s...s.s..',
  ],
  b_volcano: [
    '.....rr.....',
    '....rRRr....',
    '....syys....',
    '...ssyyss...',
    '..sssssss...',
    '.sssssssss..',
    'sssssssssss.',
    'ssssssssssss',
  ],
  b_starfall: [
    'y.........y.',
    '.y.......y..',
    '..yy....y...',
    '...yyy.y....',
    '....yyy.....',
    '.....rr.....',
    '....rrrr....',
    '.....rr.....',
  ],
  v_hourglass: [
    '.ssssssss...',
    '..yyyyyy....',
    '...yyyy.....',
    '....yy......',
    '....yy......',
    '...y..y.....',
    '..yyyyyy....',
    '.ssssssss...',
  ],
  v_warning: [
    '.....rr.....',
    '....rwwr....',
    '....rwwr....',
    '...rrwwrr...',
    '...rrwwrr...',
    '..rrrrrrrr..',
    '..rrrwwrrr..',
    '.rrrrrrrrrr.',
  ],
  v_tag: ['..ssssssss..', '.swwwwwwwws.', 'swwoowowwws.', 'swwwwwwwwws.', '.swwwwwwwws.', '..ssssssss..'],
  v_bubble: [
    '...wwwwww...',
    '..wwwwwwww..',
    '.wwowwowoww.',
    '.wwwwwwwwww.',
    '..wwwwwwww..',
    '...wwwww....',
    '..ww........',
    '.w..........',
  ],
  v_paw: [
    '..s....s....',
    '.sss..sss...',
    '..s....s....',
    's...ss...s..',
    'ss.ssss.ss..',
    '...ssssss...',
    '....ssss....',
  ],
  v_grid: [
    's...s...s...',
    'ssssssssssss',
    's...s...s...',
    's...s...s...',
    'ssssssssssss',
    's...s...s...',
    's...s...s...',
    'ssssssssssss',
  ],
  v_eye: ['............', '...wwwwww...', '.wwwbbbbwww.', 'wwwbbobbbwww', '.wwwbbbbwww.', '...wwwwww...'],
} satisfies Record<string, string[]>
