// Farming, items and divine powers: 12x12 pixel art, one string per row, letters index the palette.
export const farmAndPowerSprites = {
  horse: [
    '.........RR.',
    '........oRRR',
    '.......oRRoR',
    'o.RRRRRRRR..',
    'oRRRRRRRRR..',
    '.RRRRRRRR...',
    '.R.R...R.R..',
    '.R.R...R.R..',
    '.o.o...o.o..',
  ],
  chicken: [
    '......rr....',
    '.....www....',
    '.....wowy...',
    '..wwwwww....',
    '.wwwwwww....',
    '..wwwww.....',
    '...y.y......',
  ],
  search: [
    '...wwww.....',
    '..w....w....',
    '.w..bb..w...',
    '.w.b....w...',
    '.w......w...',
    '..w....w....',
    '...wwwws....',
    '.......sss..',
    '........sss.',
    '.........ss.',
  ],
  save: [
    '.BBBBBBBBB..',
    '.BwwwwwwoB..',
    '.BwwwwwwoB..',
    '.BwwwwwwwB..',
    '.BBBBBBBBB..',
    '.BBsssssBB..',
    '.BBsoossBB..',
    '.BBsoossBB..',
    '.BBBBBBBBB..',
  ],
  pill: [
    '.......ooo..',
    '......orrro.',
    '.....orrrro.',
    '....owrrro..',
    '...owwwoo...',
    '..owwwwo....',
    '.owwwwo.....',
    '.owwwo......',
    '..ooo.......',
  ],
  wheat: [
    '....y.y.y...',
    '...yy.y.yy..',
    '....yyyyy...',
    '...yy.y.yy..',
    '....yyyyy...',
    '.....yyy....',
    '......s.....',
    '......s.....',
    '.....s.s....',
    '....s...s...',
  ],
  thaw: [
    '......b.....',
    '.....bBb....',
    '......b.....',
    '....g.......',
    '...gGg......',
    '....G.......',
    'RsRsGsRsRsRs',
    'sRssRssRssRs',
    'ssssssssssss',
  ],
  village: [
    '..r.....r...',
    '.rrr...rrr..',
    'rrrrr.rrrrr.',
    '.wBw...wBw..',
    '.www.r.www..',
    '....rrr.....',
    '...rrrrr....',
    '....wBw.....',
    '....www.....',
  ],
  plea: [
    '..wwwwwwww..',
    '.wwwwrrwwww.',
    '.wwwwrrwwww.',
    '.wwwwrrwwww.',
    '.wwwwwwwwww.',
    '.wwwwrrwwww.',
    '..wwwwwwww..',
    '...ww.......',
    '..w.........',
  ],
  blossom: [
    '...p...y....',
    '..ppp.yyy...',
    '...p...y.p..',
    '...g...g.ppp',
    '..gG..gGg.p.',
    '...G...G..g.',
    '...G...G..G.',
    'gggGgggGggGg',
  ],
  seedling: [
    '............',
    '..g...g...g.',
    '.gGg.gGg.gGg',
    '..G...G...G.',
    'ssssssssssss',
    'RRRRRRRRRRRR',
    'ssssssssssss',
    'RRRRRRRRRRRR',
  ],
  sapling: [
    '.....gg.....',
    '....gGgg....',
    '...gGggGg...',
    '....gggg....',
    '.....s......',
    '.....s......',
    '....sss.....',
    '...oooooo...',
  ],
  fruittree: [
    '....gggg....',
    '..ggrgggGg..',
    '.gGgggggrgg.',
    '.ggrgGgggGg.',
    '..gggggrgg..',
    '...gggggg...',
    '.....ss.....',
    '.....ss.....',
    '....ssss....',
  ],
  sword: [
    '.........ww.',
    '........wwo.',
    '.......wwo..',
    '......wwo...',
    '.....wwo....',
    '..y.wwo.....',
    '...yyo......',
    '...sy.......',
    '..s..y......',
    '.s..........',
  ],
  gift: [
    '...rr.rr....',
    '....rrr.....',
    '.yyyyryyyy..',
    '.yyyyryyyy..',
    '.rrrrrrrrr..',
    '.yyyyryyyy..',
    '.yyyyryyyy..',
    '.yyyyryyyy..',
    '.yyyyryyyy..',
  ],
  bucket: [
    '...sss......',
    '..s...s.....',
    '.ssssssss...',
    '.sbbbbbbs...',
    '.sbbbbbbs...',
    '..sbbbbs....',
    '..sbbbbs....',
    '...ssss.....',
    '.b.....b....',
    'b..b.b..b...',
  ],
  shield: [
    '.bbbbbbbbb..',
    '.bwwwwwwwb..',
    '.bwwyywwwb..',
    '.bwyyyywwb..',
    '.bwwyywwwb..',
    '..bwwwwwb...',
    '...bwwwb....',
    '....bwb.....',
    '.....b......',
  ],
  ward: [
    '...yyyyyy...',
    '..y......y..',
    '.y...r....y.',
    'y...rrr....y',
    'y..rrrrr...y',
    'y..wwyww...y',
    'y..wwBww...y',
    'y..wwRww...y',
    'gggggggggggg',
    'GGGGGGGGGGGG',
  ],
  revive: [
    '....yyyy....',
    '...y....y...',
    '...y....y...',
    '....yyyy....',
    '.....yy.....',
    '..yyyyyyyy..',
    '.....yy.....',
    '.....yy.....',
    '.....yy.....',
    '....oyyo....',
  ],
  angry: [
    '...rrrrr....',
    '..rrrrrrr...',
    '.ro.rrr.or..',
    '.rrorrrorr..',
    '.rrrrrrrrr..',
    '.rrrooorrr..',
    '.rrorrrorr..',
    '..rrrrrrr...',
    '...rrrrr....',
  ],
  thunder: [
    '...www......',
    '..wwwww.ww..',
    '.wwwwwwwwww.',
    '.ssssssssss.',
    '.....yy.....',
    '....yy......',
    '...yyyy.....',
    '.....yy.....',
    '....yy......',
    '...y........',
  ],
  wilt: [
    '.......RR...',
    '......RRpR..',
    '......RRR...',
    '.....s......',
    '....s.......',
    '...s..s.....',
    '...s.s......',
    '...ss.......',
    '...s........',
    '..sss.......',
  ],
  wave: [
    '......bbbb..',
    '....bbwwwbb.',
    '...bbw...wb.',
    '..bbw.......',
    '.bbbb..b....',
    'bbbbbbbbb.b.',
    'BBBBBBBBBBBB',
    'BBBBBBBBBBBB',
  ],
} satisfies Record<string, string[]>
