// People tools (family): 12x12 pixel art, one string per row, letters index the palette.
export const peopleSprites = {
  family: [
    '............',
    '..oo....oo..',
    '.oyyo..oyyo.',
    '.oyyo..oyyo.',
    '..oBBo.oBBo.',
    '..oBBo.oBBo.',
    '..oBBo.oBBo.',
    '...oo..oo...',
    '....oyyo....',
    '....orro....',
    '....orro....',
    '....oo.oo...',
  ],
  teleport: [
    '.....pp.....',
    '...pp..pp...',
    '..p......p..',
    '.p...bb...p.',
    '.p..bBBb..p.',
    'p...bBBb...p',
    'p...bBBb...p',
    '.p..bBBb..p.',
    '.p...bb...p.',
    '..p......p..',
    '...pp..pp...',
    '.....pp.....',
  ],
  footprints: [
    '............',
    '..oo.oo.....',
    '..oyyo.oyy..',
    '..oo.oo.....',
    '..oyo.oyo...',
    '...oo..oo...',
    '............',
    '.....oo.oo..',
    '....oyy.oyo.',
    '.....oo.oo..',
    '............',
    '............',
  ],
} as const
