// Terrain, wildlife and weather: 12x12 pixel art, one string per row, letters index the palette.
export const worldSprites = {
  person: [
    '....yyy.....',
    '....yoy.....',
    '.....s......',
    '...bbbbb....',
    '...bbybb....',
    '...sbbb.s...',
    '....BBB.....',
    '....B.B.....',
    '...BB.BB....',
    '...oo.oo....',
  ],
  house: [
    '.....r......',
    '....rrr.....',
    '...rryrr....',
    '..rryyyrr...',
    '.RRRRRRRRR..',
    '..wywwwyw...',
    '..wBwwwBw...',
    '..wwwRwww...',
    '..wwwRwww...',
    '..sssssss...',
  ],
  mountain: [
    '......w.....',
    '.....www....',
    '....wswsw...',
    '...ssssss...',
    '..Gsssssss..',
    '.GGGsssssss.',
    'GGyGGssGsssG',
    'GGGGGGGGGGGG',
  ],
  apple: [
    '......GG....',
    '.....sG.....',
    '..rrr.rrr...',
    '.ryrrrrrrr..',
    '.ryrrrrrrr..',
    '.rrrrrrrrr..',
    '..rrrrrrR...',
    '...RRRRR....',
  ],
  map: [
    '.yyyywwyyyy.',
    '.ybbywwyGGy.',
    '.ybbywwGGGy.',
    '.yGGywwyGyy.',
    '.GGGywbyyyy.',
    '.yGyywbbyGy.',
    '.yyyywwyGGy.',
    '.yyyywwyyyy.',
  ],
  cursor: [
    '..w.........',
    '..ww........',
    '..wyw.......',
    '..wyyw......',
    '..wyyyw.....',
    '..wyyyyw....',
    '..wywwww....',
    '..wwyw......',
    '.....yw.....',
    '.....ww.....',
  ],
  plus: [
    '....yy......',
    '....yy......',
    '....yy......',
    '.yyyyyyyy...',
    '.yyyyyyyy...',
    '....yy......',
    '....yy......',
    '....yy......',
  ],
  tribe: [
    '..yyy.yyy...',
    '..yoy.yoy...',
    '...s...s....',
    '.bbbbbGGGGG.',
    '.bbybbGGyGG.',
    '..BBB.GGG...',
    '..B.B.G.G...',
    '.BB.BBG.GG..',
  ],
  heart: [
    '..rrr.rrr...',
    '.rwrrrrrrr..',
    '.rwrrrrrrr..',
    '.rrrrrrrrr..',
    '..rrrrrrR...',
    '...rrrrR....',
    '....rrR.....',
    '.....R......',
  ],
  skull: [
    '...wwwww....',
    '..wwwwwww...',
    '.wwwswwwww..',
    '.woowwooww..',
    '.woowwooww..',
    '..wwwowww...',
    '...wwwww....',
    '...w.w.w....',
  ],
  fire: [
    '.....r......',
    '.....ry.....',
    '...r.ryr....',
    '...ryyyr....',
    '..rryyyrr...',
    '.rryyyyyrr..',
    '.rryywyyrr..',
    '..rrwwwrr...',
    '...RRRRR....',
    '.sss..sss...',
  ],
  grass: [
    '..g...g.....',
    '...g.g..g...',
    '.g.ggg.g....',
    '..ggggggg...',
    '.GGGGGGGGG..',
    '.sssssssss..',
    '..sssssss...',
  ],
  water: [
    '............',
    '.bb...bb....',
    'bBBb.bBBb.b.',
    '...bb...bb..',
    '.bb...bb....',
    'bBBb.bBBb.b.',
    '...bb...bb..',
  ],
  rock: ['...sssss....', '..swwwsss...', '.swwssssss..', '.sssssssss..', '..ssssssso..', '...oooooo...'],
  sand: ['............', '....yyyy....', '..yyyyyyyy..', '.yyysyyysy..', '..yyyyyyy...', '...sssss....'],
  snow: [
    '.....w......',
    '..w..w..w...',
    '...w.w.w....',
    '....www.....',
    '.wwwwwwwww..',
    '....www.....',
    '...w.w.w....',
    '..w..w..w...',
    '.....w......',
  ],
  drop: [
    '.....b......',
    '....bbb.....',
    '....bbb.....',
    '...bwbbb....',
    '..bwwbbbb...',
    '..bwbbbbb...',
    '...bbBBB....',
    '....BBB.....',
  ],
  border: [
    '...yyyyy....',
    '..y.....y...',
    '.y.......y..',
    '.y..GGG..y..',
    '.y..GGG..y..',
    '.y.......y..',
    '..y.....y...',
    '...yyyyy....',
  ],
  swords: [
    '.w.......w..',
    '.ww.....ww..',
    '..ww...ww...',
    '...ww.ww....',
    '....www.....',
    '...ywwwy....',
    '..yyy.yyy...',
    '...s...s....',
    '..s.....s...',
  ],
  route: ['.yy.........', '...y........', '...y..yyyy..', '...yyyy..y..', '.........yy.'],
  compass: [
    '...yyyyy....',
    '..yswwwsy...',
    '.yswwrwwsy..',
    '.ywwwrwwwy..',
    '.ywwrrrwwy..',
    '.ywwwBwwwy..',
    '.yswwBwwsy..',
    '..yswwwsy...',
    '...yyyyy....',
  ],
  deer: [
    '..s.s...s.s.',
    '...ss...ss..',
    '....s...s...',
    '....sssss...',
    '....sosss...',
    '.ssssssss...',
    '.sssssss....',
    '..s..s......',
    '..s..s......',
  ],
  rabbit: [
    '....w.w.....',
    '....wpw.....',
    '....wpw.....',
    '....www.....',
    '...wwwow....',
    '.wwwwww.....',
    '.wwwwwww....',
    '..sssssss...',
  ],
  boar: ['...s...s....', '..sssssss...', '.ssssssoss..', '.sssssssyw..', '..sssssss...', '..s.s.s.s...'],
  wolf: [
    '...s...s....',
    '...ss.ss....',
    '...swsws....',
    '.sssssoos...',
    '.ssssssww...',
    '..ssssss....',
    '..s..s......',
  ],
  bird: ['.....bbb....', '....bwoby...', '..bbbbb.....', '.bBBBBb.....', '...bbb......', '....ss......'],
  fox: [
    '.........r.r',
    '........rrrr',
    'wwrrrrrrrrro',
    'wwrrrrrrrrrr',
    '..rrrrrrrrr.',
    '...rrrrrrr..',
    '..R.R...R.R.',
    '..o.o...o.o.',
  ],
  fog: [
    '..wwwwww....',
    '.wwwwwwwwww.',
    '............',
    'wwwwwwwwww..',
    '............',
    '...wwwwwwwww',
    '............',
    '.wwwwwwww...',
  ],
  wind: ['.ssssss.....', '..........ss', '..ssssssss..', '.......sssss', '..ssssss....', '...........s'],
  snowman: [
    '.....www....',
    '.....wow....',
    '.....www....',
    '....wwwww...',
    '...wwwwwww..',
    '...wwwwwww..',
    '....wwwww...',
  ],
  berry: [
    '...gggggg...',
    '..gggggggg..',
    '.gggrggrggg.',
    '.grggggggrg.',
    '.gGggrgggGg.',
    '..GGGGGGGG..',
    '.....ss.....',
  ],
  mushroom: [
    '....rrrrrr..',
    '..rrrwrrrrr.',
    '.rwrrrrrrwrr',
    '.rrrrrrrrrrr',
    '.....wsw....',
    '.....wsw....',
    '....wwsww...',
    '..oooooooo..',
  ],
  eraser: [
    '.........oo.',
    '........opoo',
    '.......opppo',
    '......opppp.',
    '.....opppp..',
    '....opppo...',
    '...oppoo....',
    '...oooo.....',
  ],
  dog: [
    '.........s..',
    '........ssss',
    '...sssssssso',
    '.ssssssssss.',
    '.sssssssss..',
    '..s.s..s.s..',
    '..o.o..o.o..',
  ],
  cat: [
    '........s.s.',
    '........ssss',
    's......ssoss',
    'ss.sssssssss',
    '.sssssssssss',
    '..s.s..s.s..',
    '..o.o..o.o..',
  ],
  fish: ['....bbbbb...', 'b..bwwbbbb..', 'bbbwwbbbob..', 'bbbBBBBBBB..', 'b..BBBBBB...', '....BBBB....'],
  rain: [
    '...wwwww....',
    '..wwwwwww...',
    '.sswwwwsss..',
    '.sssssssss..',
    '............',
    '..b..b..b...',
    '.b..b..b....',
  ],
  storm: [
    '...sssss....',
    '..sssssss...',
    '.BBBBBBBBB..',
    '....yy......',
    '...yy..b....',
    '....yyb.....',
    '...yy.......',
    '...y........',
  ],
  sun: [
    '.....y......',
    '..y.....y...',
    '....yyy.....',
    '...yyyyy....',
    '.y.yyyyy.y..',
    '...yyyyy....',
    '....yyy.....',
    '..y.....y...',
    '.....y......',
  ],
} satisfies Record<string, string[]>
