// Terrain, wildlife and weather: 12x12 pixel art, one string per row, letters index the palette.
export const worldSprites = {
  person: [
    '....yyy.....',
    '....yoy.....',
    '.....s......',
    '...bbbbb....',
    '...bbybb....',
    '...sbbb.s...',
    '....BBB.....',
    '....B.B.....',
    '...BB.BB....',
    '...oo.oo....',
  ],
  house: [
    '.....r......',
    '....rrr.....',
    '...rryrr....',
    '..rryyyrr...',
    '.RRRRRRRRR..',
    '..wywwwyw...',
    '..wBwwwBw...',
    '..wwwRwww...',
    '..wwwRwww...',
    '..sssssss...',
  ],
  mountain: [
    '......w.....',
    '.....www....',
    '....wswsw...',
    '...ssssss...',
    '..Gsssssss..',
    '.GGGsssssss.',
    'GGyGGssGsssG',
    'GGGGGGGGGGGG',
  ],
  apple: [
    '......GG....',
    '.....sG.....',
    '..rrr.rrr...',
    '.ryrrrrrrr..',
    '.ryrrrrrrr..',
    '.rrrrrrrrr..',
    '..rrrrrrR...',
    '...RRRRR....',
  ],
  map: [
    '.yyyywwyyyy.',
    '.ybbywwyGGy.',
    '.ybbywwGGGy.',
    '.yGGywwyGyy.',
    '.GGGywbyyyy.',
    '.yGyywbbyGy.',
    '.yyyywwyGGy.',
    '.yyyywwyyyy.',
  ],
  cursor: [
    '..w.........',
    '..ww........',
    '..wyw.......',
    '..wyyw......',
    '..wyyyw.....',
    '..wyyyyw....',
    '..wywwww....',
    '..wwyw......',
    '.....yw.....',
    '.....ww.....',
  ],
  plus: [
    '....yy......',
    '....yy......',
    '....yy......',
    '.yyyyyyyy...',
    '.yyyyyyyy...',
    '....yy......',
    '....yy......',
    '....yy......',
  ],
  tribe: [
    '..yyy.yyy...',
    '..yoy.yoy...',
    '...s...s....',
    '.bbbbbGGGGG.',
    '.bbybbGGyGG.',
    '..BBB.GGG...',
    '..B.B.G.G...',
    '.BB.BBG.GG..',
  ],
  heart: [
    '..rrr.rrr...',
    '.rwrrrrrrr..',
    '.rwrrrrrrr..',
    '.rrrrrrrrr..',
    '..rrrrrrR...',
    '...rrrrR....',
    '....rrR.....',
    '.....R......',
  ],
  skull: [
    '...wwwww....',
    '..wwwwwww...',
    '.wwwswwwww..',
    '.woowwooww..',
    '.woowwooww..',
    '..wwwowww...',
    '...wwwww....',
    '...w.w.w....',
  ],
  fire: [
    '.....r......',
    '.....ry.....',
    '...r.ryr....',
    '...ryyyr....',
    '..rryyyrr...',
    '.rryyyyyrr..',
    '.rryywyyrr..',
    '..rrwwwrr...',
    '...RRRRR....',
    '.sss..sss...',
  ],
  grass: [
    '..g...g.....',
    '...g.g..g...',
    '.g.ggg.g....',
    '..ggggggg...',
    '.GGGGGGGGG..',
    '.sssssssss..',
    '..sssssss...',
  ],
  water: [
    '............',
    '.bb...bb....',
    'bBBb.bBBb.b.',
    '...bb...bb..',
    '.bb...bb....',
    'bBBb.bBBb.b.',
    '...bb...bb..',
  ],
  rock: ['...sssss....', '..swwwsss...', '.swwssssss..', '.sssssssss..', '..ssssssso..', '...oooooo...'],
  sand: ['............', '....yyyy....', '..yyyyyyyy..', '.yyysyyysy..', '..yyyyyyy...', '...sssss....'],
  snow: [
    '.....w......',
    '..w..w..w...',
    '...w.w.w....',
    '....www.....',
    '.wwwwwwwww..',
    '....www.....',
    '...w.w.w....',
    '..w..w..w...',
    '.....w......',
  ],
  lava: [
    '............',
    '.....o......',
    '....orr.....',
    '..oorryo....',
    '.orryyyro...',
    'oryyyyyrro..',
    'oRyyyyyyRo..',
    'oRRRRRRRRo..',
    '.oooooooo...',
    '............',
  ],
  drop: [
    '.....b......',
    '....bbb.....',
    '....bbb.....',
    '...bwbbb....',
    '..bwwbbbb...',
    '..bwbbbbb...',
    '...bbBBB....',
    '....BBB.....',
  ],
  border: [
    '...yyyyy....',
    '..y.....y...',
    '.y.......y..',
    '.y..GGG..y..',
    '.y..GGG..y..',
    '.y.......y..',
    '..y.....y...',
    '...yyyyy....',
  ],
  swords: [
    '.w.......w..',
    '.ww.....ww..',
    '..ww...ww...',
    '...ww.ww....',
    '....www.....',
    '...ywwwy....',
    '..yyy.yyy...',
    '...s...s....',
    '..s.....s...',
  ],
  route: ['.yy.........', '...y........', '...y..yyyy..', '...yyyy..y..', '.........yy.'],
  compass: [
    '...yyyyy....',
    '..yswwwsy...',
    '.yswwrwwsy..',
    '.ywwwrwwwy..',
    '.ywwrrrwwy..',
    '.ywwwBwwwy..',
    '.yswwBwwsy..',
    '..yswwwsy...',
    '...yyyyy....',
  ],
  caravan: [
    '............',
    '..oooooooo..',
    '..orrrrrro..',
    '..orwwwwro..',
    '..orwwwwro..',
    '..oooooooo..',
    '...ss..ss...',
    '...ss..ss...',
    '............',
    '............',
    '............',
    '............',
  ],
  deer: [
    '..s.s...s.s.',
    '...ss...ss..',
    '....s...s...',
    '....sssss...',
    '....sosss...',
    '.ssssssss...',
    '.sssssss....',
    '..s..s......',
    '..s..s......',
  ],
  rabbit: [
    '....w.w.....',
    '....wpw.....',
    '....wpw.....',
    '....www.....',
    '...wwwow....',
    '.wwwwww.....',
    '.wwwwwww....',
    '..sssssss...',
  ],
  boar: ['...s...s....', '..sssssss...', '.ssssssoss..', '.sssssssyw..', '..sssssss...', '..s.s.s.s...'],
  wolf: [
    '...s...s....',
    '...ss.ss....',
    '...swsws....',
    '.sssssoos...',
    '.ssssssww...',
    '..ssssss....',
    '..s..s......',
  ],
  bird: ['.....bbb....', '....bwoby...', '..bbbbb.....', '.bBBBBb.....', '...bbb......', '....ss......'],
  bandage: [
    '............',
    '............',
    '...rrrrrr...',
    '..rwwwwwwr..',
    '.rwwrrrrwwr.',
    '.rwwrwwrwwr.',
    '.rwwrrrrwwr.',
    '..rwwwwwwr..',
    '...rrrrrr...',
    '............',
    '............',
    '............',
  ],
  guard_dog: [
    '............',
    '.ss......ss.',
    '.sss....sss.',
    '.ssssssssss.',
    '.sosssssoss.',
    '.ssssyyssss.',
    '..ssoyyoss..',
    '...ssssss...',
    '............',
    '............',
    '............',
    '............',
  ],
  broom: [
    '...........o',
    '..........ss',
    '.........ss.',
    '........ss..',
    '.......ss...',
    '......ss....',
    '.....yyyy...',
    '....yyoyyy..',
    '...yyyyyyyy.',
    '...oyoyoyo..',
    '............',
    '............',
  ],
  snake: [
    '............',
    '..ggggggg...',
    '.gG.....gg..',
    '.g.......g..',
    '.g.....gg...',
    '..gggggg....',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
  ],
  crocodile: [
    '............',
    '............',
    '.gggggggggg.',
    'ggGGGGGGGGGo',
    '.gggggggggg.',
    '.g.g....g.g.',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
  ],
  goat: [
    '............',
    '.........ww.',
    '.........ss.',
    '.....ssssss.',
    '....ssssssss',
    '....ssssssss',
    '.....ssssss.',
    '.....s..s...',
    '.....s..s...',
    '.....o..o...',
    '............',
    '............',
  ],
  elephant: [
    '............',
    '............',
    '..ssssssss..',
    '.ssssssssss.',
    'sssssssssssw',
    'sssssssssss.',
    '.ssssssssss.',
    '.s.s....s.s.',
    '.o.o....o.o.',
    '............',
    '............',
    '............',
  ],
  monkey: [
    '............',
    '....RRRR....',
    '..RRRRRRRR..',
    '.RRyyyyyyRR.',
    '.RyoyyyyoyR.',
    '.RyyyyyyyyR.',
    '..RyyoooyR..',
    '...RRRRRR...',
    '..RRRRRRRR..',
    '.RRRRRRRRRR.',
    '.RRR....RRR.',
    '.RR......RR.',
  ],
  owl: [
    '............',
    '..o......o..',
    '.oso....oso.',
    '.ossssssssso.',
    '.osyyssyyso.',
    '.ossssssssso.',
    '.ossssssssso.',
    '..oooooooo..',
    '...y....y...',
    '............',
    '............',
    '............',
  ],
  eagle: [
    '............',
    '..RR....RR..',
    '.RRRR..RRRR.',
    '.RRRRRRRRRR.',
    '..RRwwwwRR..',
    '..RwwyywRR..',
    '...RRRRRR...',
    '.....yy.....',
    '............',
    '............',
    '............',
    '............',
  ],
  heat_wave: [
    '.....oo.....',
    '....orro....',
    '....orro....',
    '....orro....',
    '....orro....',
    '....orro....',
    '...orrrro...',
    '..orrrrrro..',
    '..orrrrrro..',
    '...oooooo...',
    '............',
    '............',
  ],
  duck: [
    '............',
    '.......ooo..',
    '......oyyyo.',
    '.....oyyyyrr',
    '....oyyyyyo.',
    '..ooyyyyyyo.',
    '.oyyyyyyyyyo',
    '.oyyyyyyyyo.',
    '..ooooooooo.',
    '...o.....o..',
    '............',
    '............',
  ],
  bee: [
    '............',
    '..ww....ww..',
    '...ww..ww...',
    '....oooooo..',
    '...oyyyyyo..',
    '..oyyoyyyyo.',
    '..oooyyoooo.',
    '...oyyyyyo..',
    '....oooooo..',
    '.....oo.....',
    '............',
    '............',
  ],
  rain_cloud: [
    '............',
    '....wwwww...',
    '..wwwwwwwww.',
    '.wwwwwwwwwww',
    '.wwwwwwwwwwo',
    '............',
    '..b.....b...',
    '.b.....b....',
    '............',
    '...b.....b..',
    '..b.....b...',
    '............',
  ],
  merge: [
    '............',
    'b.........b.',
    'bb.......bb.',
    '.bb.....bb..',
    '..bb...bb...',
    '...bb.bb....',
    '....bbb.....',
    '....yyy.....',
    '....yyy.....',
    '....yyy.....',
    '............',
    '............',
  ],
  split: [
    '............',
    '............',
    '....yyy.....',
    '....yyy.....',
    '....bbb.....',
    '...bb.bb....',
    '..bb...bb...',
    '.bb.....bb..',
    'bb.......bb.',
    'b.........b.',
    '............',
    '............',
  ],
  dna: [
    '......r.....',
    '...ryyyyb...',
    '...r....b...',
    '....r..b....',
    '....byyr....',
    '...b....r...',
    '...b....r...',
    '.....rb.....',
    '...r....b...',
    '...r....b...',
    '....ryyb....',
    '....b..r....',
  ],
  scroll: [
    '............',
    '..ooooooooo.',
    '.owwwwwwwwo.',
    '.owyyyyyyw.o',
    '.owwwwwwwwo.',
    '.owyyyyyyyo.',
    '.owwwwwwwwo.',
    '.owyyyyyyw.o',
    '.owwwwwwwwo.',
    '..ooooooooo.',
    '............',
    '............',
  ],
  charm: [
    '............',
    '..oooooooo..',
    '.owwwwwwwwo.',
    'owwwBBBBwwwo',
    'owwBBooBBwwo',
    'owwwBBBBwwwo',
    '.owwwwwwwwo.',
    '..oooooooo..',
    '............',
    '............',
    '............',
    '............',
  ],
  hail: [
    '............',
    '...oooooo...',
    '..owwwwwwo..',
    '.owwwwwwwwo.',
    '.oooooooooo.',
    '...b..b..b..',
    '..b..b..b...',
    '...b..b..b..',
    '............',
    '............',
    '............',
    '............',
  ],
  nuke: [
    '....oooo....',
    '..oorrrroo..',
    '.orrrRRrrro.',
    '.orrRRRRrro.',
    '..oooooooo..',
    '.....oo.....',
    '.....oo.....',
    '....oooo....',
    '............',
    '............',
    '............',
    '............',
  ],
  penguin: [
    '............',
    '.....oo.....',
    '....oooo....',
    '...oooooo...',
    '...owwwwo...',
    '...owwwwo...',
    '..owwwwwwo..',
    '..owwwwwwo..',
    '..ooooooo...',
    '...yy.yy....',
    '............',
    '............',
  ],
  camel: [
    '............',
    '.ss....ss...',
    '.ss....ss...',
    'ssssssssss..',
    'ssssssssssss',
    'ssssssssssss',
    '.ssssssssss.',
    '.s.s....s.s.',
    '.o.o....o.o.',
    '............',
  ],
  frog: [
    '............',
    '.ggg....ggg.',
    '.gwo....owg.',
    'gggggggggggg',
    'gGgggggggggG',
    '.gggggggggg.',
    'G.GG....GG.G',
  ],
  whale: [
    '............',
    '.....w......',
    '....BBB.....',
    '..BBBBBBBB..',
    '.BBBBBBBBBBB',
    'BBobBBBBBBBB',
    'bbbbbbbbbbbb',
    '.bbbbbbbbbb.',
    '..bbbbbbbb..',
    '............',
    '............',
    '............',
  ],
  fox: [
    '.........r.r',
    '........rrrr',
    'wwrrrrrrrrro',
    'wwrrrrrrrrrr',
    '..rrrrrrrrr.',
    '...rrrrrrr..',
    '..R.R...R.R.',
    '..o.o...o.o.',
  ],
  acorn: ['....gggg....', '...gggggg...', '..gggggggg..', '..GGGGGGGG..', '...ssssss...', '....ssss....'],
  pine: [
    '.....g......',
    '....ggg.....',
    '...ggggg....',
    '....ggg.....',
    '..ggggggg...',
    '.ggggggggg..',
    '....sss.....',
  ],
  coconut: ['....ssss....', '...sssssss..', '..ssssssssss', '..sssssssss.', '...ssssss...', '....ssss....'],
  log: [
    '..........oo',
    '.........oyy',
    '.........oyy',
    '.yyyyyyyyoyy',
    'oyyyyyyyyyyo',
    'oooooooooooo',
    '..........oo',
  ],
  lion: [
    '...yyyy.....',
    '..yyyyyy....',
    '.yyyyyyyy...',
    '.yyoyyoyy...',
    '.yyyyyyyy...',
    '.yyyyypyy...',
    '..yyyyyy....',
    '..y.y..y.y..',
  ],
  locust: [
    '..gg....gg..',
    '...gg..gg...',
    '....gggg....',
    '...gggggg...',
    '..gggooggg..',
    '..gggggggg..',
    '..gg.gg.gg..',
    '.g..g..g..g.',
  ],
  tsunami: [
    '.....sss....',
    '...sssssss..',
    '..ssssssssss',
    '.ssssssssss.',
    'bbbbbbbbbbbb',
    'bBbbbBbbbbBb',
    'BBbbbbbBbbbB',
    'BBBBBBBBBBBB',
  ],
  tornado: [
    '.ssssssssss.',
    '..ssssssss..',
    '...ssssss...',
    '.....ss.....',
    '....sss.....',
    '....ss......',
    '...sss......',
    '...s........',
  ],
  fog: [
    '..wwwwww....',
    '.wwwwwwwwww.',
    '............',
    'wwwwwwwwww..',
    '............',
    '...wwwwwwwww',
    '............',
    '.wwwwwwww...',
  ],
  wind: ['.ssssss.....', '..........ss', '..ssssssss..', '.......sssss', '..ssssss....', '...........s'],
  snowman: [
    '.....www....',
    '.....wow....',
    '.....www....',
    '....wwwww...',
    '...wwwwwww..',
    '...wwwwwww..',
    '....wwwww...',
  ],
  berry: [
    '...gggggg...',
    '..gggggggg..',
    '.gggrggrggg.',
    '.grggggggrg.',
    '.gGggrgggGg.',
    '..GGGGGGGG..',
    '.....ss.....',
  ],
  mushroom: [
    '....rrrrrr..',
    '..rrrwrrrrr.',
    '.rwrrrrrrwrr',
    '.rrrrrrrrrrr',
    '.....wsw....',
    '.....wsw....',
    '....wwsww...',
    '..oooooooo..',
  ],
  road: [
    '............',
    '.........yy.',
    '.......yssy.',
    '....yyssssy.',
    '...yssssyy..',
    '..yssssy....',
    '.yssssy.....',
    'yssssy......',
    'yssy........',
    'yy..........',
    '............',
    '............',
  ],
  bridge: [
    '............',
    '............',
    '............',
    '.oooooooooo.',
    '.yyyyyyyyyy.',
    '.syyyyyyyys.',
    'oooooooooooo',
    '.o........o.',
    'BBBBBBBBBBBB',
    'BBBBBBBBBBBB',
    '............',
    '............',
  ],
  coin: [
    '............',
    '....oooo....',
    '..oyyyyyyo..',
    '.oyyyoyyyyo.',
    '.oyyoyyyyyo.',
    '.oyyyyyyyyo.',
    '.oyyyyyyyyo.',
    '.oyyyyyyyyo.',
    '.oyyyyyyyyo.',
    '.oyyyyyyyyo.',
    '..oyyyyyyo..',
    '....oooo....',
  ],
  eraser: [
    '.........oo.',
    '........opoo',
    '.......opppo',
    '......opppp.',
    '.....opppp..',
    '....opppo...',
    '...oppoo....',
    '...oooo.....',
  ],
  dog: [
    '.........s..',
    '........ssss',
    '...sssssssso',
    '.ssssssssss.',
    '.sssssssss..',
    '..s.s..s.s..',
    '..o.o..o.o..',
  ],
  cat: [
    '........s.s.',
    '........ssss',
    's......ssoss',
    'ss.sssssssss',
    '.sssssssssss',
    '..s.s..s.s..',
    '..o.o..o.o..',
  ],
  fish: ['....bbbbb...', 'b..bwwbbbb..', 'bbbwwbbbob..', 'bbbBBBBBBB..', 'b..BBBBBB...', '....BBBB....'],
  rain: [
    '...wwwww....',
    '..wwwwwww...',
    '.sswwwwsss..',
    '.sssssssss..',
    '............',
    '..b..b..b...',
    '.b..b..b....',
  ],
  storm: [
    '...sssss....',
    '..sssssss...',
    '.BBBBBBBBB..',
    '....yy......',
    '...yy..b....',
    '....yyb.....',
    '...yy.......',
    '...y........',
  ],
  sun: [
    '.....y......',
    '..y.....y...',
    '....yyy.....',
    '...yyyyy....',
    '.y.yyyyy.y..',
    '...yyyyy....',
    '....yyy.....',
    '..y.....y...',
    '.....y......',
  ],
} satisfies Record<string, string[]>
