use crate::sim::era::Era;

pub struct TechNode {
    pub name: &'static str,
    pub era: Era,
    pub prerequisites: &'static [&'static str],
    pub unlocks: &'static [&'static str],
    pub discovery_rate: f32,
}

static TECH: &[TechNode] = &[
    TechNode { name: "foraging",                era: Era::PreStone, prerequisites: &[],                                       unlocks: &["basket_weaving"],     discovery_rate: 8.0 },
    TechNode { name: "fire",                    era: Era::Stone,    prerequisites: &[],                                       unlocks: &["cooking", "torch"],   discovery_rate: 6.0 },
    TechNode { name: "stone_tools",             era: Era::Stone,    prerequisites: &["fire"],                                 unlocks: &["tool_making"],        discovery_rate: 5.0 },
    TechNode { name: "shelter",                 era: Era::Stone,    prerequisites: &["foraging"],                             unlocks: &["masonry"],            discovery_rate: 5.0 },
    TechNode { name: "language",                era: Era::Stone,    prerequisites: &["foraging"],                             unlocks: &["writing"],            discovery_rate: 4.5 },
    TechNode { name: "tool_making",             era: Era::Stone,    prerequisites: &["stone_tools"],                          unlocks: &["fishing", "hunting"], discovery_rate: 4.0 },
    TechNode { name: "fishing",                 era: Era::Stone,    prerequisites: &["tool_making"],                          unlocks: &[],                     discovery_rate: 3.5 },
    TechNode { name: "hunting",                 era: Era::Stone,    prerequisites: &["tool_making"],                          unlocks: &["leather"],            discovery_rate: 4.5 },
    TechNode { name: "basket_weaving",          era: Era::Stone,    prerequisites: &["foraging"],                             unlocks: &["weaving"],            discovery_rate: 4.0 },
    TechNode { name: "leather",                 era: Era::Stone,    prerequisites: &["hunting"],                              unlocks: &[],                     discovery_rate: 3.0 },
    TechNode { name: "body_paint",              era: Era::Stone,    prerequisites: &["foraging"],                             unlocks: &["dye"],                discovery_rate: 2.5 },

    TechNode { name: "smelting",                era: Era::Bronze,   prerequisites: &["fire", "stone_tools"],                  unlocks: &["ironworking"],        discovery_rate: 2.5 },
    TechNode { name: "pottery",                 era: Era::Bronze,   prerequisites: &["fire"],                                 unlocks: &["ceramics"],           discovery_rate: 3.0 },
    TechNode { name: "agriculture",             era: Era::Bronze,   prerequisites: &["foraging"],                             unlocks: &["plowing", "brewing"], discovery_rate: 4.0 },
    TechNode { name: "animal_domestication",    era: Era::Bronze,   prerequisites: &["hunting"],                              unlocks: &["plowing"],            discovery_rate: 2.5 },
    TechNode { name: "weaving",                 era: Era::Bronze,   prerequisites: &["basket_weaving"],                       unlocks: &["dye"],                discovery_rate: 4.0 },
    TechNode { name: "wheel",                   era: Era::Bronze,   prerequisites: &["tool_making"],                          unlocks: &["plowing"],            discovery_rate: 2.0 },
    TechNode { name: "sail",                    era: Era::Bronze,   prerequisites: &["weaving"],                              unlocks: &["navigation"],         discovery_rate: 1.8 },
    TechNode { name: "plowing",                 era: Era::Bronze,   prerequisites: &["agriculture", "animal_domestication"],  unlocks: &[],                     discovery_rate: 2.0 },
    TechNode { name: "dye",                     era: Era::Bronze,   prerequisites: &["weaving"],                              unlocks: &[],                     discovery_rate: 2.0 },
    TechNode { name: "salt",                    era: Era::Bronze,   prerequisites: &["foraging"],                             unlocks: &[],                     discovery_rate: 2.0 },
    TechNode { name: "candle",                  era: Era::Bronze,   prerequisites: &["fire"],                                 unlocks: &[],                     discovery_rate: 2.0 },
    TechNode { name: "ceramics",                era: Era::Bronze,   prerequisites: &["pottery"],                              unlocks: &[],                     discovery_rate: 1.8 },
    TechNode { name: "brewing",                 era: Era::Bronze,   prerequisites: &["agriculture"],                          unlocks: &[],                     discovery_rate: 3.5 },
    TechNode { name: "navigation",              era: Era::Bronze,   prerequisites: &["sail"],                                 unlocks: &["cartography"],        discovery_rate: 1.5 },

    TechNode { name: "ironworking",             era: Era::Iron,     prerequisites: &["smelting"],                             unlocks: &["masonry"],            discovery_rate: 2.0 },
    TechNode { name: "writing",                 era: Era::Iron,     prerequisites: &["language"],                             unlocks: &["alphabet"],           discovery_rate: 3.5 },
    TechNode { name: "alphabet",                era: Era::Iron,     prerequisites: &["writing"],                              unlocks: &["library_concept"],    discovery_rate: 1.8 },
    TechNode { name: "glass",                   era: Era::Iron,     prerequisites: &["smelting"],                             unlocks: &["telescope"],          discovery_rate: 1.6 },
    TechNode { name: "masonry",                 era: Era::Iron,     prerequisites: &["shelter", "ironworking"],               unlocks: &["arch", "aqueduct"],   discovery_rate: 1.8 },
    TechNode { name: "road_building",           era: Era::Iron,     prerequisites: &["masonry", "wheel"],                     unlocks: &[],                     discovery_rate: 1.5 },
    TechNode { name: "calendar",                era: Era::Iron,     prerequisites: &["writing", "astronomy"],                 unlocks: &[],                     discovery_rate: 1.4 },
    TechNode { name: "currency",                era: Era::Iron,     prerequisites: &["writing"],                              unlocks: &["double_entry_bookkeeping"], discovery_rate: 1.6 },
    TechNode { name: "mathematics",             era: Era::Iron,     prerequisites: &["writing"],                              unlocks: &["geometry", "physics"], discovery_rate: 1.8 },
    TechNode { name: "philosophy",              era: Era::Iron,     prerequisites: &["writing"],                              unlocks: &["democracy"],          discovery_rate: 1.5 },
    TechNode { name: "astronomy",               era: Era::Iron,     prerequisites: &["mathematics"],                          unlocks: &["astronomy_helio"],    discovery_rate: 1.4 },
    TechNode { name: "engineering",             era: Era::Iron,     prerequisites: &["mathematics", "masonry"],               unlocks: &["aqueduct", "dome"],   discovery_rate: 1.4 },
    TechNode { name: "irrigation",              era: Era::Iron,     prerequisites: &["agriculture", "masonry"],               unlocks: &[],                     discovery_rate: 1.6 },
    TechNode { name: "aqueduct",                era: Era::Iron,     prerequisites: &["engineering"],                          unlocks: &["plumbing"],           discovery_rate: 1.2 },
    TechNode { name: "plumbing",                era: Era::Iron,     prerequisites: &["aqueduct"],                             unlocks: &[],                     discovery_rate: 1.2 },
    TechNode { name: "mosaic",                  era: Era::Iron,     prerequisites: &["ceramics"],                             unlocks: &[],                     discovery_rate: 1.2 },

    TechNode { name: "democracy",               era: Era::Classical, prerequisites: &["philosophy"],                          unlocks: &["law_code"],           discovery_rate: 1.2 },
    TechNode { name: "theater",                 era: Era::Classical, prerequisites: &["writing"],                             unlocks: &["opera"],              discovery_rate: 1.2 },
    TechNode { name: "library_concept",         era: Era::Classical, prerequisites: &["alphabet"],                            unlocks: &["university_concept"], discovery_rate: 1.0 },
    TechNode { name: "surgery",                 era: Era::Classical, prerequisites: &["anatomy"],                             unlocks: &["anesthesia"],         discovery_rate: 0.9 },
    TechNode { name: "anatomy",                 era: Era::Classical, prerequisites: &["philosophy"],                          unlocks: &["anatomy_modern"],     discovery_rate: 1.0 },
    TechNode { name: "geometry",                era: Era::Classical, prerequisites: &["mathematics"],                         unlocks: &["perspective_drawing"], discovery_rate: 1.2 },
    TechNode { name: "physics",                 era: Era::Classical, prerequisites: &["mathematics"],                         unlocks: &["chemistry"],          discovery_rate: 1.0 },
    TechNode { name: "chemistry",               era: Era::Classical, prerequisites: &["physics"],                             unlocks: &["alchemy"],            discovery_rate: 0.9 },
    TechNode { name: "law_code",                era: Era::Classical, prerequisites: &["writing", "democracy"],                unlocks: &[],                     discovery_rate: 1.0 },
    TechNode { name: "columns",                 era: Era::Classical, prerequisites: &["masonry"],                             unlocks: &[],                     discovery_rate: 1.0 },
    TechNode { name: "dome",                    era: Era::Classical, prerequisites: &["arch"],                                unlocks: &[],                     discovery_rate: 0.9 },
    TechNode { name: "arch",                    era: Era::Classical, prerequisites: &["masonry"],                             unlocks: &["dome"],               discovery_rate: 1.0 },
    TechNode { name: "cement",                  era: Era::Classical, prerequisites: &["masonry"],                             unlocks: &[],                     discovery_rate: 1.0 },

    TechNode { name: "feudalism",               era: Era::Medieval, prerequisites: &["law_code"],                             unlocks: &["heraldry"],           discovery_rate: 1.0 },
    TechNode { name: "heraldry",                era: Era::Medieval, prerequisites: &["feudalism"],                            unlocks: &[],                     discovery_rate: 0.9 },
    TechNode { name: "plate_armor",             era: Era::Medieval, prerequisites: &["ironworking"],                          unlocks: &[],                     discovery_rate: 0.9 },
    TechNode { name: "longbow",                 era: Era::Medieval, prerequisites: &["hunting"],                              unlocks: &[],                     discovery_rate: 0.9 },
    TechNode { name: "windmill",                era: Era::Medieval, prerequisites: &["engineering"],                          unlocks: &["mill"],               discovery_rate: 1.0 },
    TechNode { name: "watermill",               era: Era::Medieval, prerequisites: &["engineering"],                          unlocks: &["mill"],               discovery_rate: 1.0 },
    TechNode { name: "mill",                    era: Era::Medieval, prerequisites: &["windmill"],                             unlocks: &[],                     discovery_rate: 1.0 },
    TechNode { name: "plow",                    era: Era::Medieval, prerequisites: &["plowing", "ironworking"],               unlocks: &[],                     discovery_rate: 1.0 },
    TechNode { name: "paper",                   era: Era::Medieval, prerequisites: &["writing"],                              unlocks: &["printing"],           discovery_rate: 1.0 },
    TechNode { name: "university_concept",      era: Era::Medieval, prerequisites: &["library_concept"],                      unlocks: &[],                     discovery_rate: 0.8 },
    TechNode { name: "gothic_architecture",     era: Era::Medieval, prerequisites: &["arch", "engineering"],                  unlocks: &[],                     discovery_rate: 0.8 },
    TechNode { name: "alchemy",                 era: Era::Medieval, prerequisites: &["chemistry"],                            unlocks: &["scientific_method"],  discovery_rate: 0.9 },
    TechNode { name: "magnetic_compass",        era: Era::Medieval, prerequisites: &["navigation"],                           unlocks: &["exploration"],        discovery_rate: 0.9 },
    TechNode { name: "gunpowder",               era: Era::Medieval, prerequisites: &["alchemy"],                              unlocks: &["dynamite"],           discovery_rate: 0.9 },

    TechNode { name: "printing",                era: Era::Renaissance, prerequisites: &["paper"],                             unlocks: &[],                     discovery_rate: 0.9 },
    TechNode { name: "telescope",               era: Era::Renaissance, prerequisites: &["glass"],                             unlocks: &["astronomy_helio"],    discovery_rate: 0.8 },
    TechNode { name: "microscope",              era: Era::Renaissance, prerequisites: &["glass"],                             unlocks: &["germ_theory"],        discovery_rate: 0.8 },
    TechNode { name: "perspective_drawing",     era: Era::Renaissance, prerequisites: &["geometry"],                          unlocks: &["oil_painting"],       discovery_rate: 0.8 },
    TechNode { name: "double_entry_bookkeeping", era: Era::Renaissance, prerequisites: &["currency"],                         unlocks: &[],                     discovery_rate: 0.8 },
    TechNode { name: "oil_painting",            era: Era::Renaissance, prerequisites: &["perspective_drawing"],               unlocks: &[],                     discovery_rate: 0.7 },
    TechNode { name: "opera",                   era: Era::Renaissance, prerequisites: &["theater"],                           unlocks: &[],                     discovery_rate: 0.6 },
    TechNode { name: "scientific_method",       era: Era::Renaissance, prerequisites: &["alchemy", "philosophy"],             unlocks: &[],                     discovery_rate: 0.9 },
    TechNode { name: "anatomy_modern",          era: Era::Renaissance, prerequisites: &["anatomy"],                           unlocks: &[],                     discovery_rate: 0.7 },
    TechNode { name: "cartography",             era: Era::Renaissance, prerequisites: &["navigation"],                        unlocks: &["exploration"],        discovery_rate: 0.8 },
    TechNode { name: "exploration",             era: Era::Renaissance, prerequisites: &["cartography", "magnetic_compass"],   unlocks: &[],                     discovery_rate: 0.8 },
    TechNode { name: "astronomy_helio",         era: Era::Renaissance, prerequisites: &["telescope"],                         unlocks: &[],                     discovery_rate: 0.7 },

    TechNode { name: "steam_engine",            era: Era::Industrial, prerequisites: &["scientific_method"],                  unlocks: &["railroad", "factory"], discovery_rate: 1.6 },
    TechNode { name: "railroad",                era: Era::Industrial, prerequisites: &["steam_engine"],                       unlocks: &[],                     discovery_rate: 1.6 },
    TechNode { name: "factory",                 era: Era::Industrial, prerequisites: &["steam_engine"],                       unlocks: &["sewing_machine"],     discovery_rate: 1.6 },
    TechNode { name: "telegraph",               era: Era::Industrial, prerequisites: &["electricity_generation"],             unlocks: &["telephone"],          discovery_rate: 1.4 },
    TechNode { name: "photography",             era: Era::Industrial, prerequisites: &["chemistry"],                          unlocks: &["motion_picture"],     discovery_rate: 1.2 },
    TechNode { name: "internal_combustion",     era: Era::Industrial, prerequisites: &["steam_engine"],                       unlocks: &["automobile", "airplane"], discovery_rate: 1.4 },
    TechNode { name: "electricity_generation",  era: Era::Industrial, prerequisites: &["scientific_method"],                  unlocks: &["telegraph", "telephone"], discovery_rate: 1.6 },
    TechNode { name: "electricity",             era: Era::Industrial, prerequisites: &["electricity_generation"],             unlocks: &[],                     discovery_rate: 1.6 },
    TechNode { name: "vaccine",                 era: Era::Industrial, prerequisites: &["germ_theory"],                        unlocks: &[],                     discovery_rate: 0.6 },
    TechNode { name: "anesthesia",              era: Era::Industrial, prerequisites: &["surgery", "chemistry"],               unlocks: &[],                     discovery_rate: 0.6 },
    TechNode { name: "germ_theory",             era: Era::Industrial, prerequisites: &["microscope"],                         unlocks: &["antibiotics"],        discovery_rate: 0.6 },
    TechNode { name: "dynamite",                era: Era::Industrial, prerequisites: &["gunpowder", "chemistry"],             unlocks: &[],                     discovery_rate: 0.6 },
    TechNode { name: "sewer",                   era: Era::Industrial, prerequisites: &["plumbing", "germ_theory"],            unlocks: &[],                     discovery_rate: 0.6 },
    TechNode { name: "sewing_machine",          era: Era::Industrial, prerequisites: &["factory"],                            unlocks: &[],                     discovery_rate: 0.6 },
    TechNode { name: "bicycle",                 era: Era::Industrial, prerequisites: &["factory"],                            unlocks: &[],                     discovery_rate: 0.6 },

    TechNode { name: "telephone",               era: Era::Modern, prerequisites: &["telegraph"],                              unlocks: &[],                     discovery_rate: 1.4 },
    TechNode { name: "radio",                   era: Era::Modern, prerequisites: &["electricity_generation"],                 unlocks: &["television"],         discovery_rate: 1.4 },
    TechNode { name: "automobile",              era: Era::Modern, prerequisites: &["internal_combustion"],                    unlocks: &[],                     discovery_rate: 1.2 },
    TechNode { name: "airplane",                era: Era::Modern, prerequisites: &["internal_combustion"],                    unlocks: &["jet_engine"],         discovery_rate: 1.0 },
    TechNode { name: "motion_picture",          era: Era::Modern, prerequisites: &["photography"],                            unlocks: &[],                     discovery_rate: 1.0 },
    TechNode { name: "antibiotics",             era: Era::Modern, prerequisites: &["germ_theory"],                            unlocks: &[],                     discovery_rate: 1.4 },
    TechNode { name: "plastic",                 era: Era::Modern, prerequisites: &["chemistry"],                              unlocks: &[],                     discovery_rate: 1.0 },
    TechNode { name: "refrigeration",           era: Era::Modern, prerequisites: &["electricity"],                            unlocks: &[],                     discovery_rate: 1.0 },
    TechNode { name: "nuclear_fission",         era: Era::Modern, prerequisites: &["physics", "scientific_method"],           unlocks: &[],                     discovery_rate: 0.8 },
    TechNode { name: "computer_concept",        era: Era::Modern, prerequisites: &["mathematics", "electricity"],             unlocks: &["computer"],           discovery_rate: 1.2 },
    TechNode { name: "television",              era: Era::Modern, prerequisites: &["radio"],                                  unlocks: &[],                     discovery_rate: 1.0 },
    TechNode { name: "jet_engine",              era: Era::Modern, prerequisites: &["airplane"],                               unlocks: &[],                     discovery_rate: 1.0 },

    TechNode { name: "computer",                era: Era::Information, prerequisites: &["computer_concept"],                  unlocks: &["internet", "AI"],     discovery_rate: 1.2 },
    TechNode { name: "internet",                era: Era::Information, prerequisites: &["computer", "telephone"],             unlocks: &["social_media"],       discovery_rate: 1.2 },
    TechNode { name: "satellite",               era: Era::Information, prerequisites: &["jet_engine", "radio"],               unlocks: &["GPS"],                discovery_rate: 1.0 },
    TechNode { name: "smartphone",              era: Era::Information, prerequisites: &["computer", "telephone"],             unlocks: &[],                     discovery_rate: 0.4 },
    TechNode { name: "gene_editing",            era: Era::Information, prerequisites: &["anatomy_modern", "computer"],        unlocks: &[],                     discovery_rate: 0.3 },
    TechNode { name: "AI",                      era: Era::Information, prerequisites: &["computer"],                          unlocks: &[],                     discovery_rate: 0.3 },
    TechNode { name: "GPS",                     era: Era::Information, prerequisites: &["satellite"],                         unlocks: &[],                     discovery_rate: 0.4 },
    TechNode { name: "social_media",            era: Era::Information, prerequisites: &["internet"],                          unlocks: &[],                     discovery_rate: 0.4 },
    TechNode { name: "renewable_energy",        era: Era::Information, prerequisites: &["electricity_generation"],            unlocks: &[],                     discovery_rate: 0.4 },

    TechNode { name: "rocketry",                era: Era::Atomic, prerequisites: &["internal_combustion", "chemistry"], unlocks: &["spaceflight"], discovery_rate: 0.4 },
    TechNode { name: "telescopes",              era: Era::Atomic, prerequisites: &["telescope", "satellite"], unlocks: &[], discovery_rate: 0.4 },
    TechNode { name: "spaceflight",             era: Era::Space, prerequisites: &["rocketry", "satellite"], unlocks: &["satellite_network"], discovery_rate: 0.35 },
    TechNode { name: "satellite_network",       era: Era::Space, prerequisites: &["spaceflight"], unlocks: &[], discovery_rate: 0.35 },
    TechNode { name: "microchip",               era: Era::Digital, prerequisites: &["computer", "AI"], unlocks: &["mobile", "cloud"], discovery_rate: 0.35 },
    TechNode { name: "mobile",                  era: Era::Digital, prerequisites: &["smartphone", "microchip"], unlocks: &[], discovery_rate: 0.35 },
    TechNode { name: "cloud",                   era: Era::Digital, prerequisites: &["internet", "microchip"], unlocks: &[], discovery_rate: 0.35 },
    TechNode { name: "quantum_compute",         era: Era::Quantum, prerequisites: &["microchip", "physics"], unlocks: &["crypto", "entanglement"], discovery_rate: 0.3 },
    TechNode { name: "crypto",                  era: Era::Quantum, prerequisites: &["quantum_compute"], unlocks: &[], discovery_rate: 0.3 },
    TechNode { name: "entanglement",            era: Era::Quantum, prerequisites: &["quantum_compute"], unlocks: &[], discovery_rate: 0.3 },
    TechNode { name: "solar_grid",              era: Era::Solar, prerequisites: &["renewable_energy"], unlocks: &["battery_grid"], discovery_rate: 0.3 },
    TechNode { name: "battery_grid",            era: Era::Solar, prerequisites: &["solar_grid"], unlocks: &["smart_grid"], discovery_rate: 0.3 },
    TechNode { name: "smart_grid",              era: Era::Solar, prerequisites: &["battery_grid", "AI"], unlocks: &[], discovery_rate: 0.3 },
    TechNode { name: "tokamak",                 era: Era::Fusion, prerequisites: &["nuclear_fission", "smart_grid"], unlocks: &["fusion_reactor"], discovery_rate: 0.25 },
    TechNode { name: "fusion_reactor",          era: Era::Fusion, prerequisites: &["tokamak"], unlocks: &["helium3"], discovery_rate: 0.25 },
    TechNode { name: "helium3",                 era: Era::Fusion, prerequisites: &["fusion_reactor", "spaceflight"], unlocks: &[], discovery_rate: 0.25 },
    TechNode { name: "biotech",                 era: Era::Genetic, prerequisites: &["gene_editing"], unlocks: &["genome_edit"], discovery_rate: 0.25 },
    TechNode { name: "genome_edit",             era: Era::Genetic, prerequisites: &["biotech"], unlocks: &["cloning"], discovery_rate: 0.25 },
    TechNode { name: "cloning",                 era: Era::Genetic, prerequisites: &["genome_edit"], unlocks: &[], discovery_rate: 0.25 },
    TechNode { name: "space_elevator",          era: Era::Orbital, prerequisites: &["spaceflight", "fusion_reactor"], unlocks: &["orbital_ring"], discovery_rate: 0.2 },
    TechNode { name: "orbital_ring",            era: Era::Orbital, prerequisites: &["space_elevator"], unlocks: &["orbital_factory"], discovery_rate: 0.2 },
    TechNode { name: "orbital_factory",         era: Era::Orbital, prerequisites: &["orbital_ring"], unlocks: &[], discovery_rate: 0.2 },
    TechNode { name: "moon_base",               era: Era::Lunar, prerequisites: &["space_elevator"], unlocks: &["lunar_mining"], discovery_rate: 0.2 },
    TechNode { name: "lunar_mining",            era: Era::Lunar, prerequisites: &["moon_base"], unlocks: &["low_gravity"], discovery_rate: 0.2 },
    TechNode { name: "low_gravity",             era: Era::Lunar, prerequisites: &["moon_base"], unlocks: &[], discovery_rate: 0.2 },
    TechNode { name: "interplanetary",          era: Era::Martian, prerequisites: &["moon_base"], unlocks: &["mars_colony"], discovery_rate: 0.18 },
    TechNode { name: "mars_colony",             era: Era::Martian, prerequisites: &["interplanetary"], unlocks: &["terraforming"], discovery_rate: 0.18 },
    TechNode { name: "terraforming",            era: Era::Martian, prerequisites: &["mars_colony", "biotech"], unlocks: &[], discovery_rate: 0.18 },
    TechNode { name: "cybernetics",             era: Era::Cyber, prerequisites: &["anatomy_modern", "microchip"], unlocks: &["augmentation"], discovery_rate: 0.18 },
    TechNode { name: "neural_interface",        era: Era::Cyber, prerequisites: &["cybernetics", "AI"], unlocks: &["brain_upload"], discovery_rate: 0.18 },
    TechNode { name: "augmentation",            era: Era::Cyber, prerequisites: &["cybernetics"], unlocks: &[], discovery_rate: 0.18 },
    TechNode { name: "brain_upload",            era: Era::Neural, prerequisites: &["neural_interface"], unlocks: &["synthetic_mind"], discovery_rate: 0.15 },
    TechNode { name: "synthetic_mind",          era: Era::Neural, prerequisites: &["brain_upload", "AI"], unlocks: &["consciousness_net"], discovery_rate: 0.15 },
    TechNode { name: "consciousness_net",       era: Era::Neural, prerequisites: &["synthetic_mind"], unlocks: &[], discovery_rate: 0.15 },
    TechNode { name: "longevity",               era: Era::Posthuman, prerequisites: &["genome_edit"], unlocks: &["synthetic_body"], discovery_rate: 0.14 },
    TechNode { name: "synthetic_body",          era: Era::Posthuman, prerequisites: &["longevity", "cybernetics"], unlocks: &[], discovery_rate: 0.14 },
    TechNode { name: "post_scarcity",           era: Era::Posthuman, prerequisites: &["fusion_reactor", "AI"], unlocks: &[], discovery_rate: 0.14 },
    TechNode { name: "warp",                    era: Era::Interstellar, prerequisites: &["fusion_reactor", "quantum_compute"], unlocks: &["generation_ship"], discovery_rate: 0.12 },
    TechNode { name: "generation_ship",         era: Era::Interstellar, prerequisites: &["space_elevator", "post_scarcity"], unlocks: &["exoplanet"], discovery_rate: 0.12 },
    TechNode { name: "exoplanet",               era: Era::Interstellar, prerequisites: &["generation_ship"], unlocks: &[], discovery_rate: 0.12 },
    TechNode { name: "agi",                     era: Era::Singularity, prerequisites: &["AI", "consciousness_net"], unlocks: &["self_improvement"], discovery_rate: 0.1 },
    TechNode { name: "self_improvement",        era: Era::Singularity, prerequisites: &["agi"], unlocks: &["transcend"], discovery_rate: 0.1 },
    TechNode { name: "transcend",               era: Era::Singularity, prerequisites: &["self_improvement"], unlocks: &[], discovery_rate: 0.1 },
    TechNode { name: "dyson_swarm",             era: Era::Galactic, prerequisites: &["space_elevator", "fusion_reactor"], unlocks: &["dyson_sphere"], discovery_rate: 0.09 },
    TechNode { name: "galactic_net",            era: Era::Galactic, prerequisites: &["agi", "entanglement"], unlocks: &[], discovery_rate: 0.09 },
    TechNode { name: "kardashev2",              era: Era::Galactic, prerequisites: &["dyson_swarm"], unlocks: &[], discovery_rate: 0.09 },
    TechNode { name: "dyson_sphere",            era: Era::Dyson, prerequisites: &["dyson_swarm"], unlocks: &["stellar_engineering"], discovery_rate: 0.07 },
    TechNode { name: "stellar_engineering",     era: Era::Dyson, prerequisites: &["dyson_sphere"], unlocks: &["megaswarm"], discovery_rate: 0.07 },
    TechNode { name: "megaswarm",               era: Era::Dyson, prerequisites: &["stellar_engineering"], unlocks: &[], discovery_rate: 0.07 },
    TechNode { name: "stellar_harvest",         era: Era::Kardashev2, prerequisites: &["dyson_sphere"], unlocks: &["planet_lift"], discovery_rate: 0.06 },
    TechNode { name: "planet_lift",             era: Era::Kardashev2, prerequisites: &["stellar_harvest"], unlocks: &[], discovery_rate: 0.06 },
    TechNode { name: "galactic_coms",           era: Era::Kardashev2, prerequisites: &["galactic_net"], unlocks: &[], discovery_rate: 0.06 },
    TechNode { name: "galactic_engine",         era: Era::Kardashev3, prerequisites: &["stellar_harvest"], unlocks: &["star_forge"], discovery_rate: 0.05 },
    TechNode { name: "star_forge",              era: Era::Kardashev3, prerequisites: &["galactic_engine"], unlocks: &["supercluster"], discovery_rate: 0.05 },
    TechNode { name: "supercluster",            era: Era::Kardashev3, prerequisites: &["star_forge"], unlocks: &[], discovery_rate: 0.05 },
    TechNode { name: "star_lifting",            era: Era::Stellar, prerequisites: &["star_forge"], unlocks: &["stellar_remix"], discovery_rate: 0.04 },
    TechNode { name: "stellar_remix",           era: Era::Stellar, prerequisites: &["star_lifting"], unlocks: &["corona_mining"], discovery_rate: 0.04 },
    TechNode { name: "corona_mining",           era: Era::Stellar, prerequisites: &["stellar_remix"], unlocks: &[], discovery_rate: 0.04 },
    TechNode { name: "nebula_weave",            era: Era::Nebular, prerequisites: &["star_lifting"], unlocks: &["dustfold"], discovery_rate: 0.03 },
    TechNode { name: "dustfold",                era: Era::Nebular, prerequisites: &["nebula_weave"], unlocks: &["gas_husbandry"], discovery_rate: 0.03 },
    TechNode { name: "gas_husbandry",           era: Era::Nebular, prerequisites: &["dustfold"], unlocks: &[], discovery_rate: 0.03 },
    TechNode { name: "vacuum_engineering",      era: Era::Universal, prerequisites: &["nebula_weave"], unlocks: &["cosmic_strings"], discovery_rate: 0.025 },
    TechNode { name: "cosmic_strings",          era: Era::Universal, prerequisites: &["vacuum_engineering"], unlocks: &["universal_constant"], discovery_rate: 0.025 },
    TechNode { name: "universal_constant",      era: Era::Universal, prerequisites: &["cosmic_strings"], unlocks: &[], discovery_rate: 0.025 },
    TechNode { name: "branch_travel",           era: Era::Multiverse, prerequisites: &["universal_constant"], unlocks: &["timelines"], discovery_rate: 0.02 },
    TechNode { name: "timelines",               era: Era::Multiverse, prerequisites: &["branch_travel"], unlocks: &["parallel_consensus"], discovery_rate: 0.02 },
    TechNode { name: "parallel_consensus",      era: Era::Multiverse, prerequisites: &["timelines"], unlocks: &[], discovery_rate: 0.02 },
    TechNode { name: "ascension",               era: Era::Transcendent, prerequisites: &["parallel_consensus"], unlocks: &["boundary_break"], discovery_rate: 0.015 },
    TechNode { name: "boundary_break",          era: Era::Transcendent, prerequisites: &["ascension"], unlocks: &["unbeing"], discovery_rate: 0.015 },
    TechNode { name: "unbeing",                 era: Era::Transcendent, prerequisites: &["boundary_break"], unlocks: &[], discovery_rate: 0.015 },
    TechNode { name: "deep_lore",               era: Era::Eldritch, prerequisites: &["unbeing"], unlocks: &["outer_pact"], discovery_rate: 0.01 },
    TechNode { name: "outer_pact",              era: Era::Eldritch, prerequisites: &["deep_lore"], unlocks: &["abyssal_geometry"], discovery_rate: 0.01 },
    TechNode { name: "abyssal_geometry",        era: Era::Eldritch, prerequisites: &["outer_pact"], unlocks: &[], discovery_rate: 0.01 },
];

pub fn all_tech() -> &'static [TechNode] {
    TECH
}
