use super::*;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BuildingKind {
    Hut,
    House,
    Manor,
    TownHouse,
    Apartment,
    School,
    University,
    Library,
    Market,
    Temple,
    Factory,
    Hospital,
    Forge,
    Mill,
    Bakery,
    Inn,
    Bank,
    Workshop,
    Granary,
    Barracks,
    Lighthouse,
    Windmill,
    Watermill,
    Aqueduct,
    Bridge,
    Wall,
    Tower,
    Plaza,
    Statue,
    Fountain,
    TrainStation,
    Airport,
    Port,
    Stadium,
    Museum,
    Cathedral,
    Castle,
    Theatre,
    Observatory,
    Tavern,
    Brewery,
    Butcher,
    Fishmonger,
    Cheesemonger,
    Tailor,
    Cobbler,
    ClothingShop,
    Jeweler,
    Apothecary,
    Herbalist,
    Barbershop,
    Scribe,
    BookStore,
    ArtGallery,
    MusicHall,
    Cafe,
    Restaurant,
    Hotel,
    GuildHall,
    Courthouse,
    CityHall,
    PostOffice,
    PoliceStation,
    FireStation,
    Pharmacy,
    Clinic,
    Spa,
    Bathhouse,
    Greenhouse,
    Vineyard,
    Ranch,
    Stable,
    Kennel,
    Dovecote,
    Quarry,
    Mine,
    SawMill,
    Tannery,
    Smithy,
    Goldsmith,
    Refinery,
    PowerPlant,
    Substation,
    WaterTower,
    Reservoir,
    GasStation,
    AutoShop,
    Garage,
    MallShop,
    Supermarket,
    OfficeTower,
    Skyscraper,
    Datacenter,
    Studio,
    Spaceport,
    OrbitalLift,
    SolarArray,
    WindFarm,
    FusionPlant,
    NeuralHub,
    AiCore,
    Biodome,
    Cryolab,
    NanoFab,
    Hyperloop,
    Maglev,
    Hospital2,
    ResearchLab,
    Megastructure,
    Well,
    Lamppost,
    Signpost,
    MarketStall,
    FoodCart,
    Cart,
    Tent,
    Pavilion,
    Gazebo,
    Bench,
    Fence,
    Gate,
    Watchtower,
    Gallows,
    Monument,
    Obelisk,
    Shrine,
    Cemetery,
    GraveStone,
    Garden,
    Orchard,
    Pond,
    PlayGround,
    FlagPole,
    Bandstand,
    Kiosk,
    BillBoard,
    TelephonePole,
    StreetLight,
    BusStop,
    ParkingLot,
    Crosswalk,
    Pyramid,
    Ziggurat,
    Coliseum,
    TriumphalArch,
    ClockTower,
    Mosque,
    Synagogue,
    Pagoda,
    Stupa,
    Mausoleum,
    Hangar,
    Silo,
    Warehouse,
    Dock,
    Marina,
    Lighthouse2,
    Drydock,
    Crane,
    RadioTower,
    SatelliteDish,
    WindTurbine,
    SolarPanel,
    ChargingStation,
    RoboticArm,
    Drone,
    HoloBoard,
    NeonSign,
    ArcadeBox,
    Fountain2,
    FoodTruck,
    Greenhouse2,
    MushroomFarm,
    Aquaculture,
    /// A fenced pasture beside the houses, where a tribe keeps its livestock.
    Pen,
}

impl BuildingKind {
    pub fn name(self) -> &'static str {
        match self {
            BuildingKind::Hut => "hut",
            BuildingKind::House => "house",
            BuildingKind::Manor => "manor",
            BuildingKind::TownHouse => "townhouse",
            BuildingKind::Apartment => "apartment",
            BuildingKind::School => "school",
            BuildingKind::University => "university",
            BuildingKind::Library => "library",
            BuildingKind::Market => "market",
            BuildingKind::Temple => "temple",
            BuildingKind::Factory => "factory",
            BuildingKind::Hospital => "hospital",
            BuildingKind::Forge => "forge",
            BuildingKind::Mill => "mill",
            BuildingKind::Bakery => "bakery",
            BuildingKind::Inn => "inn",
            BuildingKind::Bank => "bank",
            BuildingKind::Workshop => "workshop",
            BuildingKind::Granary => "granary",
            BuildingKind::Barracks => "barracks",
            BuildingKind::Lighthouse => "lighthouse",
            BuildingKind::Windmill => "windmill",
            BuildingKind::Watermill => "watermill",
            BuildingKind::Aqueduct => "aqueduct",
            BuildingKind::Bridge => "bridge",
            BuildingKind::Wall => "wall",
            BuildingKind::Tower => "tower",
            BuildingKind::Plaza => "plaza",
            BuildingKind::Statue => "statue",
            BuildingKind::Fountain => "fountain",
            BuildingKind::TrainStation => "train_station",
            BuildingKind::Airport => "airport",
            BuildingKind::Port => "port",
            BuildingKind::Stadium => "stadium",
            BuildingKind::Museum => "museum",
            BuildingKind::Cathedral => "cathedral",
            BuildingKind::Castle => "castle",
            BuildingKind::Theatre => "theatre",
            BuildingKind::Observatory => "observatory",
            BuildingKind::Tavern => "tavern",
            BuildingKind::Brewery => "brewery",
            BuildingKind::Butcher => "butcher",
            BuildingKind::Fishmonger => "fishmonger",
            BuildingKind::Cheesemonger => "cheesemonger",
            BuildingKind::Tailor => "tailor",
            BuildingKind::Cobbler => "cobbler",
            BuildingKind::ClothingShop => "clothing_shop",
            BuildingKind::Jeweler => "jeweler",
            BuildingKind::Apothecary => "apothecary",
            BuildingKind::Herbalist => "herbalist",
            BuildingKind::Barbershop => "barbershop",
            BuildingKind::Scribe => "scribe",
            BuildingKind::BookStore => "bookstore",
            BuildingKind::ArtGallery => "art_gallery",
            BuildingKind::MusicHall => "music_hall",
            BuildingKind::Cafe => "cafe",
            BuildingKind::Restaurant => "restaurant",
            BuildingKind::Hotel => "hotel",
            BuildingKind::GuildHall => "guild_hall",
            BuildingKind::Courthouse => "courthouse",
            BuildingKind::CityHall => "city_hall",
            BuildingKind::PostOffice => "post_office",
            BuildingKind::PoliceStation => "police_station",
            BuildingKind::FireStation => "fire_station",
            BuildingKind::Pharmacy => "pharmacy",
            BuildingKind::Clinic => "clinic",
            BuildingKind::Spa => "spa",
            BuildingKind::Bathhouse => "bathhouse",
            BuildingKind::Greenhouse => "greenhouse",
            BuildingKind::Vineyard => "vineyard",
            BuildingKind::Ranch => "ranch",
            BuildingKind::Stable => "stable",
            BuildingKind::Kennel => "kennel",
            BuildingKind::Dovecote => "dovecote",
            BuildingKind::Quarry => "quarry",
            BuildingKind::Mine => "mine",
            BuildingKind::SawMill => "saw_mill",
            BuildingKind::Tannery => "tannery",
            BuildingKind::Smithy => "smithy",
            BuildingKind::Goldsmith => "goldsmith",
            BuildingKind::Refinery => "refinery",
            BuildingKind::PowerPlant => "power_plant",
            BuildingKind::Substation => "substation",
            BuildingKind::WaterTower => "water_tower",
            BuildingKind::Reservoir => "reservoir",
            BuildingKind::GasStation => "gas_station",
            BuildingKind::AutoShop => "auto_shop",
            BuildingKind::Garage => "garage",
            BuildingKind::MallShop => "mall_shop",
            BuildingKind::Supermarket => "supermarket",
            BuildingKind::OfficeTower => "office_tower",
            BuildingKind::Skyscraper => "skyscraper",
            BuildingKind::Datacenter => "datacenter",
            BuildingKind::Studio => "studio",
            BuildingKind::Spaceport => "spaceport",
            BuildingKind::OrbitalLift => "orbital_lift",
            BuildingKind::SolarArray => "solar_array",
            BuildingKind::WindFarm => "wind_farm",
            BuildingKind::FusionPlant => "fusion_plant",
            BuildingKind::NeuralHub => "neural_hub",
            BuildingKind::AiCore => "ai_core",
            BuildingKind::Biodome => "biodome",
            BuildingKind::Cryolab => "cryolab",
            BuildingKind::NanoFab => "nano_fab",
            BuildingKind::Hyperloop => "hyperloop",
            BuildingKind::Maglev => "maglev",
            BuildingKind::Hospital2 => "mega_hospital",
            BuildingKind::ResearchLab => "research_lab",
            BuildingKind::Megastructure => "megastructure",
            BuildingKind::Well => "well",
            BuildingKind::Lamppost => "lamppost",
            BuildingKind::Signpost => "signpost",
            BuildingKind::MarketStall => "market_stall",
            BuildingKind::FoodCart => "food_cart",
            BuildingKind::Cart => "cart",
            BuildingKind::Tent => "tent",
            BuildingKind::Pavilion => "pavilion",
            BuildingKind::Gazebo => "gazebo",
            BuildingKind::Bench => "bench",
            BuildingKind::Fence => "fence",
            BuildingKind::Gate => "gate",
            BuildingKind::Watchtower => "watchtower",
            BuildingKind::Gallows => "gallows",
            BuildingKind::Monument => "monument",
            BuildingKind::Obelisk => "obelisk",
            BuildingKind::Shrine => "shrine",
            BuildingKind::Cemetery => "cemetery",
            BuildingKind::GraveStone => "gravestone",
            BuildingKind::Garden => "garden",
            BuildingKind::Orchard => "orchard",
            BuildingKind::Pond => "pond",
            BuildingKind::PlayGround => "playground",
            BuildingKind::FlagPole => "flagpole",
            BuildingKind::Bandstand => "bandstand",
            BuildingKind::Kiosk => "kiosk",
            BuildingKind::BillBoard => "billboard",
            BuildingKind::TelephonePole => "telephone_pole",
            BuildingKind::StreetLight => "street_light",
            BuildingKind::BusStop => "bus_stop",
            BuildingKind::ParkingLot => "parking_lot",
            BuildingKind::Crosswalk => "crosswalk",
            BuildingKind::Pyramid => "pyramid",
            BuildingKind::Ziggurat => "ziggurat",
            BuildingKind::Coliseum => "coliseum",
            BuildingKind::TriumphalArch => "triumphal_arch",
            BuildingKind::ClockTower => "clock_tower",
            BuildingKind::Mosque => "mosque",
            BuildingKind::Synagogue => "synagogue",
            BuildingKind::Pagoda => "pagoda",
            BuildingKind::Stupa => "stupa",
            BuildingKind::Mausoleum => "mausoleum",
            BuildingKind::Hangar => "hangar",
            BuildingKind::Silo => "silo",
            BuildingKind::Warehouse => "warehouse",
            BuildingKind::Dock => "dock",
            BuildingKind::Marina => "marina",
            BuildingKind::Lighthouse2 => "harbor_light",
            BuildingKind::Drydock => "drydock",
            BuildingKind::Crane => "crane",
            BuildingKind::RadioTower => "radio_tower",
            BuildingKind::SatelliteDish => "satellite_dish",
            BuildingKind::WindTurbine => "wind_turbine",
            BuildingKind::SolarPanel => "solar_panel",
            BuildingKind::ChargingStation => "charging_station",
            BuildingKind::RoboticArm => "robotic_arm",
            BuildingKind::Drone => "drone",
            BuildingKind::HoloBoard => "holo_board",
            BuildingKind::NeonSign => "neon_sign",
            BuildingKind::ArcadeBox => "arcade",
            BuildingKind::Fountain2 => "grand_fountain",
            BuildingKind::FoodTruck => "food_truck",
            BuildingKind::Greenhouse2 => "biolab",
            BuildingKind::MushroomFarm => "mushroom_farm",
            BuildingKind::Aquaculture => "aquaculture",
            BuildingKind::Pen => "pen",
        }
    }

    pub fn all() -> &'static [BuildingKind] {
        use BuildingKind::*;
        &[
            Hut,
            House,
            Manor,
            TownHouse,
            Apartment,
            School,
            University,
            Library,
            Market,
            Temple,
            Factory,
            Hospital,
            Forge,
            Mill,
            Bakery,
            Inn,
            Bank,
            Workshop,
            Granary,
            Barracks,
            Lighthouse,
            Windmill,
            Watermill,
            Aqueduct,
            Bridge,
            Wall,
            Tower,
            Plaza,
            Statue,
            Fountain,
            TrainStation,
            Airport,
            Port,
            Stadium,
            Museum,
            Cathedral,
            Castle,
            Theatre,
            Observatory,
            Tavern,
            Brewery,
            Butcher,
            Fishmonger,
            Cheesemonger,
            Tailor,
            Cobbler,
            ClothingShop,
            Jeweler,
            Apothecary,
            Herbalist,
            Barbershop,
            Scribe,
            BookStore,
            ArtGallery,
            MusicHall,
            Cafe,
            Restaurant,
            Hotel,
            GuildHall,
            Courthouse,
            CityHall,
            PostOffice,
            PoliceStation,
            FireStation,
            Pharmacy,
            Clinic,
            Spa,
            Bathhouse,
            Greenhouse,
            Vineyard,
            Ranch,
            Stable,
            Kennel,
            Dovecote,
            Quarry,
            Mine,
            SawMill,
            Tannery,
            Smithy,
            Goldsmith,
            Refinery,
            PowerPlant,
            Substation,
            WaterTower,
            Reservoir,
            GasStation,
            AutoShop,
            Garage,
            MallShop,
            Supermarket,
            OfficeTower,
            Skyscraper,
            Datacenter,
            Studio,
            Spaceport,
            OrbitalLift,
            SolarArray,
            WindFarm,
            FusionPlant,
            NeuralHub,
            AiCore,
            Biodome,
            Cryolab,
            NanoFab,
            Hyperloop,
            Maglev,
            Hospital2,
            ResearchLab,
            Megastructure,
            Well,
            Lamppost,
            Signpost,
            MarketStall,
            FoodCart,
            Cart,
            Tent,
            Pavilion,
            Gazebo,
            Bench,
            Fence,
            Gate,
            Watchtower,
            Gallows,
            Monument,
            Obelisk,
            Shrine,
            Cemetery,
            GraveStone,
            Garden,
            Orchard,
            Pond,
            PlayGround,
            FlagPole,
            Bandstand,
            Kiosk,
            BillBoard,
            TelephonePole,
            StreetLight,
            BusStop,
            ParkingLot,
            Crosswalk,
            Pyramid,
            Ziggurat,
            Coliseum,
            TriumphalArch,
            ClockTower,
            Mosque,
            Synagogue,
            Pagoda,
            Stupa,
            Mausoleum,
            Hangar,
            Silo,
            Warehouse,
            Dock,
            Marina,
            Lighthouse2,
            Drydock,
            Crane,
            RadioTower,
            SatelliteDish,
            WindTurbine,
            SolarPanel,
            ChargingStation,
            RoboticArm,
            Drone,
            HoloBoard,
            NeonSign,
            ArcadeBox,
            Fountain2,
            FoodTruck,
            Greenhouse2,
            MushroomFarm,
            Aquaculture,
            Pen,
        ]
    }
}
