import { TILE, TILE_RGB } from '../../model/palette'
import { TILE_ID } from '../../model/terrain-ids'
import { oceanColor } from '../landscape-style'
import { terrainDetail } from '../terrain-detail'
import { varAmountForTile } from '../base-parts/tile-paint'

/**
 * The terrain tileset for the TileLayer backend: neutral pixel patterns, one set per ground kind.
 *
 * The canvas painter colours each pixel as `tileColor + shading + k`, where `k` is a small
 * additive texture term (2x2 cluster noise, a 1px dither and the surface marks from
 * `terrainDetail`). A TileLayer can only MULTIPLY a tile's texel by its per-tile tint, so the
 * atlas stores the texture as a factor in (0, 1], `f = (R + k) / (R + kmax)`, with `R` the kind's
 * typical channel value, and the tint is `colour * (R + kmax) / R`. Their product is
 * `colour * (R + k) / R`: the same texture with its amplitude scaled by `colour / R` (1 for a
 * typical tile of the kind; darker ocean gets a calmer texture, snow a slightly stronger one).
 *
 * Each kind has VARIANTS patterns. They are generated by running the production per-pixel
 * functions at pseudo-random world positions, so the texture statistics match the canvas
 * painter; cubeforge picks the variant per cell with `variants` (a hash of the cell).
 */

/** Patterns per kind. Cubeforge's variant lists hold at most 255. */
export const VARIANTS = 32

export interface TerrainKind {
  /** Base terrain id whose texture rules (noise amplitude, surface marks) the kind uses. */
  tid: number
  /** Typical channel value of the kind's colour (the tint's reference). */
  ref: number
}

function meanChannel(rgb: readonly number[]): number {
  return (rgb[0] + rgb[1] + rgb[2]) / 3
}

/** One entry per ground texture. Index = kind. */
export const TERRAIN_KINDS: readonly TerrainKind[] = [
  { tid: TILE_ID.VOID, ref: meanChannel(TILE_RGB[TILE_ID.VOID]) },
  { tid: TILE_ID.GRASS, ref: meanChannel(TILE_RGB[TILE_ID.GRASS]) },
  // Water and floodwater share a texture; ocean depth only changes the tint.
  { tid: TILE_ID.WATER, ref: meanChannel(oceanColor(100)) },
  { tid: TILE_ID.ROCK, ref: meanChannel(TILE_RGB[TILE_ID.ROCK]) },
  { tid: TILE_ID.ASH, ref: meanChannel(TILE_RGB[TILE_ID.ASH]) },
  { tid: TILE_ID.SCORCHED, ref: meanChannel(TILE_RGB[TILE_ID.SCORCHED]) },
  { tid: TILE_ID.SNOW, ref: meanChannel(TILE_RGB[TILE_ID.SNOW]) },
  { tid: TILE_ID.SAND, ref: meanChannel(TILE_RGB[TILE_ID.SAND]) },
  { tid: TILE_ID.LAVA, ref: meanChannel(TILE_RGB[TILE_ID.LAVA]) },
]

const KIND_OF_TILE = new Map<number, number>([
  [TILE_ID.VOID, 0],
  [TILE_ID.GRASS, 1],
  [TILE_ID.WATER, 2],
  [TILE_ID.FLOODED, 2],
  [TILE_ID.ROCK, 3],
  [TILE_ID.ASH, 4],
  [TILE_ID.SCORCHED, 5],
  [TILE_ID.SNOW, 6],
  [TILE_ID.SAND, 7],
  [TILE_ID.LAVA, 8],
])

/** The kind of a base terrain id (what `baseTerrainTile` returns). Unknown ids paint as void. */
export function terrainKind(baseTid: number): number {
  return KIND_OF_TILE.get(baseTid) ?? 0
}

/** TileLayer id of kind `kind`'s first pattern. Ids are atlas slot + 1; 0 means empty. */
export function kindHeadId(kind: number): number {
  return kind * VARIANTS + 1
}

/** The `variants` table for TileLayer: head id -> every pattern id of the kind. */
export function terrainVariants(): Record<number, number[]> {
  const out: Record<number, number[]> = {}
  for (let k = 0; k < TERRAIN_KINDS.length; k++) {
    const head = kindHeadId(k)
    out[head] = Array.from({ length: VARIANTS }, (_, v) => head + v)
  }
  return out
}

export interface TilesetPixels {
  width: number
  height: number
  /** RGBA, opaque, row-major. */
  data: Uint8ClampedArray
  columns: number
  /** Per kind: the texture's largest additive term, so the tint can compensate (`R + kmax`). */
  kmax: number[]
  /** Per kind: mean of the stored factor (0..1), what far-zoom averaging shows. */
  mean: number[]
}

function hash2(a: number, b: number): number {
  let h = (Math.imul(a, 374761393) + Math.imul(b, 668265263)) | 0
  h = Math.imul(h ^ (h >>> 13), 1274126177) | 0
  return (h ^ (h >>> 16)) >>> 0
}

/**
 * The additive texture term `k` of the canvas painter for pixel (gx, gy) of a tile whose texture
 * rules are those of `tid`. Same maths as `paintTileBlock`.
 */
export function textureTerm(tid: number, gx: number, gy: number): number {
  const clusterX = gx >> 1
  const clusterY = gy >> 1
  let h = (clusterX * 374761393 + clusterY * 668265263) | 0
  h = Math.imul(h ^ (h >>> 13), 1274126177) | 0
  const noise = ((((h >>> 0) & 0xff) - 128) * varAmountForTile(tid)) >> 7
  const dither = ((gx ^ gy) & 1) === 0 ? -1 : 1
  return noise + dither + terrainDetail(tid, gx, gy)
}

/**
 * The same atlas with every pattern flattened to its kind's mean factor. Shown while a tile is only
 * a few device pixels wide: the atlas is sampled with nearest filtering, so a textured tile that
 * small aliases and shimmers while the camera moves, where the canvas path filters it smooth.
 */
export function buildFlatTilesetPixels(): TilesetPixels {
  const src = terrainTilesetPixels()
  const data = new Uint8ClampedArray(src.data.length)
  for (let kind = 0; kind < TERRAIN_KINDS.length; kind++) {
    const byte = Math.round(src.mean[kind] * 255)
    for (let py = kind * TILE; py < (kind + 1) * TILE; py++) {
      for (let px = 0; px < src.width; px++) {
        const o = (py * src.width + px) * 4
        data[o] = byte
        data[o + 1] = byte
        data[o + 2] = byte
        data[o + 3] = 255
      }
    }
  }
  return { ...src, data }
}

let pixelsCache: TilesetPixels | null = null

/** The atlas pixels, built once. */
export function terrainTilesetPixels(): TilesetPixels {
  pixelsCache ??= buildTilesetPixels()
  return pixelsCache
}

/** Build the atlas pixels. Pure (no DOM), so it can be tested and reused off the main thread. */
export function buildTilesetPixels(): TilesetPixels {
  const columns = VARIANTS
  const rows = TERRAIN_KINDS.length
  const width = columns * TILE
  const height = rows * TILE
  const data = new Uint8ClampedArray(width * height * 4)
  const kmax: number[] = []
  const mean: number[] = []
  const terms = new Int16Array(VARIANTS * TILE * TILE)
  for (let kind = 0; kind < rows; kind++) {
    const { tid, ref } = TERRAIN_KINDS[kind]
    let hi = -Infinity
    for (let v = 0; v < VARIANTS; v++) {
      // Even pixel origins keep the 2x2 clusters and the dither phase as the canvas has them.
      const ox = (hash2(kind * 977 + 1, v * 31 + 7) % 4000) * 2
      const oy = (hash2(kind * 613 + 3, v * 57 + 11) % 4000) * 2
      for (let ty = 0; ty < TILE; ty++) {
        for (let tx = 0; tx < TILE; tx++) {
          const k = textureTerm(tid, ox + tx, oy + ty)
          terms[(v * TILE + ty) * TILE + tx] = k
          if (k > hi) hi = k
        }
      }
    }
    kmax.push(hi)
    let sum = 0
    for (let v = 0; v < VARIANTS; v++) {
      for (let ty = 0; ty < TILE; ty++) {
        for (let tx = 0; tx < TILE; tx++) {
          const k = terms[(v * TILE + ty) * TILE + tx]
          const f = Math.max(0, (ref + k) / (ref + hi))
          sum += f
          const px = v * TILE + tx
          const py = kind * TILE + ty
          const o = (py * width + px) * 4
          const byte = Math.round(f * 255)
          data[o] = byte
          data[o + 1] = byte
          data[o + 2] = byte
          data[o + 3] = 255
        }
      }
    }
    mean.push(sum / (VARIANTS * TILE * TILE))
  }
  return { width, height, data, columns, kmax, mean }
}
