export const AGE_STAGE_ICON: Record<string, string> = {
  infant: '👶',
  child: '🧒',
  teen: '🧑',
  adult: '🧔',
  elder: '🧓',
}

export const ERA_ICON: Record<string, string> = {
  PreStone: '🪨',
  Stone: '🛖',
  Bronze: '⚒️',
  Iron: '⚔️',
  Classical: '🏛️',
  Medieval: '🏰',
  Renaissance: '🎨',
  Industrial: '🏭',
  Modern: '⚙️',
  Information: '💻',
}

export const ASPIRATION_EMOJI: Record<string, string> = {
  seeker: '🔍',
  wanderer: '🧭',
  warrior: '⚔️',
  connector: '🤝',
  builder: '🔨',
  devout: '🕯️',
  sage: '📜',
  provider: '🌾',
  artist: '🎨',
  healer: '🌿',
}

export const ASPIRATION_TIPS: Record<string, string> = {
  seeker: 'Drawn to knowledge — pursues exploration, science, and learning.',
  wanderer: 'Restless and curious — happiest on the road, far from settlements.',
  warrior: 'Born for conflict — gravitates toward combat and military life.',
  connector: 'Lives for others — seeks partnerships, friendships, family.',
  builder: 'Wants to make things — construction and craft are their calling.',
  devout: 'A spiritual life — religion, ritual, and devotion guide them.',
  sage: 'A teacher at heart — passes knowledge to the next generation.',
  provider: 'Tends the household — agriculture, food, and family care.',
  artist: 'Makes for the sake of making — paintings, song, written words.',
  healer: 'Tends the sick — medicine, herbs, and the long patience of care.',
}

export const ZODIAC_GLYPH: Record<string, string> = {
  ember: '🜂',
  wave: '🜄',
  stone: '🜃',
  root: '꙰',
  bough: 'ᛉ',
  crane: 'ᛯ',
  wolf: 'ᛯ',
  dawn: '☼',
  hearth: 'ᚦ',
  veil: 'ᛏ',
  spear: 'ᛇ',
  seed: '᛫',
}

export const ZODIAC_FLAVOR: Record<string, string> = {
  ember: 'warm-hearted and quick to act',
  wave: 'fluid, patient, follows the moon',
  stone: 'steady, slow to anger, slow to fall',
  root: 'drawn deep, holds onto kin',
  bough: 'reaches outward, growing always',
  crane: 'watchful, long memory, careful step',
  wolf: 'hunts in silence, trusts the pack',
  dawn: 'born of light, restless until day',
  hearth: 'keeps the fire, tends the home',
  veil: 'quiet, sees what others miss',
  spear: 'true-aimed, blunt, unafraid',
  seed: 'small now, but everything is coming',
}

export const TOOL_ICON: Record<string, string> = {
  StoneAxe: '🪓',
  BronzeSpear: '🔱',
  IronSword: '⚔️',
  Plow: '🚜',
  Musket: '🔫',
  Rifle: '🎯',
  Book: '📕',
  Computer: '💻',
  Bow: '🏹',
  Hammer: '🔨',
  Wheel: '☸️',
  stone_axe: '🪓',
  bronze_spear: '🔱',
  iron_sword: '⚔️',
  plow: '🚜',
  musket: '🔫',
  rifle: '🎯',
  book: '📕',
  computer: '💻',
  bow: '🏹',
  hammer: '🔨',
  wheel: '☸️',
  mash: '🌾',
  wash: '🫙',
  spirit: '🥃',
  aged_spirit: '🛢️',
  blended_spirit: '🍷',
  bottled_spirit: '🍾',
  bottle: '🍶',
  meat: '🥩',
  cuts: '🔪',
  ground: '🍖',
  sausage: '🌭',
  preserved: '🧂',
  preserved_meat: '🧂',
  pattern: '📐',
  piece: '🧵',
  garment: '👕',
  lead: '🔎',
  quote: '💬',
  herb: '🌿',
  potion: '🧪',
  salve: '🧴',
  bandage: '🩹',
  candle: '🕯️',
  basket: '🧺',
  rope: '🪢',
  net: '🥅',
  pot: '🪴',
  bread: '🍞',
  cheese: '🧀',
  fish: '🐟',
  egg: '🥚',
  honey: '🍯',
  wine: '🍷',
  ale: '🍺',
  paint: '🎨',
  scroll: '📜',
  draft: '📝',
  article: '📰',
  coffee: '☕',
  milk: '🥛',
  drink: '🍵',
  pastry: '🥐',
  stock: '📦',
  incident: '🚨',
}
