const palette: Record<string, string> = {
  o: '#332c29',
  g: '#86ab59',
  G: '#4e743c',
  y: '#efd28a',
  b: '#75b6ce',
  B: '#416d91',
  r: '#cd6950',
  R: '#8e4036',
  w: '#eee5cc',
  s: '#aa9680',
  p: '#b38aae',
}

const sprites = {
  person: [
    '....yyy.....',
    '....yoy.....',
    '.....s......',
    '...bbbbb....',
    '...bbybb....',
    '...sbbb.s...',
    '....BBB.....',
    '....B.B.....',
    '...BB.BB....',
    '...oo.oo....',
  ],
  house: [
    '.....r......',
    '....rrr.....',
    '...rryrr....',
    '..rryyyrr...',
    '.RRRRRRRRR..',
    '..wywwwyw...',
    '..wBwwwBw...',
    '..wwwRwww...',
    '..wwwRwww...',
    '..sssssss...',
  ],
  mountain: [
    '......w.....',
    '.....www....',
    '....wswsw...',
    '...ssssss...',
    '..Gsssssss..',
    '.GGGsssssss.',
    'GGyGGssGsssG',
    'GGGGGGGGGGGG',
  ],
  apple: [
    '......GG....',
    '.....sG.....',
    '..rrr.rrr...',
    '.ryrrrrrrr..',
    '.ryrrrrrrr..',
    '.rrrrrrrrr..',
    '..rrrrrrR...',
    '...RRRRR....',
  ],
  map: [
    '.yyyywwyyyy.',
    '.ybbywwyGGy.',
    '.ybbywwGGGy.',
    '.yGGywwyGyy.',
    '.GGGywbyyyy.',
    '.yGyywbbyGy.',
    '.yyyywwyGGy.',
    '.yyyywwyyyy.',
  ],
  cursor: [
    '..w.........',
    '..ww........',
    '..wyw.......',
    '..wyyw......',
    '..wyyyw.....',
    '..wyyyyw....',
    '..wywwww....',
    '..wwyw......',
    '.....yw.....',
    '.....ww.....',
  ],
  plus: [
    '....yy......',
    '....yy......',
    '....yy......',
    '.yyyyyyyy...',
    '.yyyyyyyy...',
    '....yy......',
    '....yy......',
    '....yy......',
  ],
  tribe: [
    '..yyy.yyy...',
    '..yoy.yoy...',
    '...s...s....',
    '.bbbbbGGGGG.',
    '.bbybbGGyGG.',
    '..BBB.GGG...',
    '..B.B.G.G...',
    '.BB.BBG.GG..',
  ],
  heart: [
    '..rrr.rrr...',
    '.rwrrrrrrr..',
    '.rwrrrrrrr..',
    '.rrrrrrrrr..',
    '..rrrrrrR...',
    '...rrrrR....',
    '....rrR.....',
    '.....R......',
  ],
  skull: [
    '...wwwww....',
    '..wwwwwww...',
    '.wwwswwwww..',
    '.woowwooww..',
    '.woowwooww..',
    '..wwwowww...',
    '...wwwww....',
    '...w.w.w....',
  ],
  fire: [
    '.....r......',
    '.....ry.....',
    '...r.ryr....',
    '...ryyyr....',
    '..rryyyrr...',
    '.rryyyyyrr..',
    '.rryywyyrr..',
    '..rrwwwrr...',
    '...RRRRR....',
    '.sss..sss...',
  ],
  grass: [
    '..g...g.....',
    '...g.g..g...',
    '.g.ggg.g....',
    '..ggggggg...',
    '.GGGGGGGGG..',
    '.sssssssss..',
    '..sssssss...',
  ],
  water: [
    '............',
    '.bb...bb....',
    'bBBb.bBBb.b.',
    '...bb...bb..',
    '.bb...bb....',
    'bBBb.bBBb.b.',
    '...bb...bb..',
  ],
  rock: ['...sssss....', '..swwwsss...', '.swwssssss..', '.sssssssss..', '..ssssssso..', '...oooooo...'],
  sand: ['............', '....yyyy....', '..yyyyyyyy..', '.yyysyyysy..', '..yyyyyyy...', '...sssss....'],
  snow: [
    '.....w......',
    '..w..w..w...',
    '...w.w.w....',
    '....www.....',
    '.wwwwwwwww..',
    '....www.....',
    '...w.w.w....',
    '..w..w..w...',
    '.....w......',
  ],
  drop: [
    '.....b......',
    '....bbb.....',
    '....bbb.....',
    '...bwbbb....',
    '..bwwbbbb...',
    '..bwbbbbb...',
    '...bbBBB....',
    '....BBB.....',
  ],
  border: [
    '...yyyyy....',
    '..y.....y...',
    '.y.......y..',
    '.y..GGG..y..',
    '.y..GGG..y..',
    '.y.......y..',
    '..y.....y...',
    '...yyyyy....',
  ],
  swords: [
    '.w.......w..',
    '.ww.....ww..',
    '..ww...ww...',
    '...ww.ww....',
    '....www.....',
    '...ywwwy....',
    '..yyy.yyy...',
    '...s...s....',
    '..s.....s...',
  ],
  route: ['.yy.........', '...y........', '...y..yyyy..', '...yyyy..y..', '.........yy.'],
  compass: [
    '...yyyyy....',
    '..yswwwsy...',
    '.yswwrwwsy..',
    '.ywwwrwwwy..',
    '.ywwrrrwwy..',
    '.ywwwBwwwy..',
    '.yswwBwwsy..',
    '..yswwwsy...',
    '...yyyyy....',
  ],
  deer: [
    '..s.s...s.s.',
    '...ss...ss..',
    '....s...s...',
    '....sssss...',
    '....sosss...',
    '.ssssssss...',
    '.sssssss....',
    '..s..s......',
    '..s..s......',
  ],
  rabbit: [
    '....w.w.....',
    '....wpw.....',
    '....wpw.....',
    '....www.....',
    '...wwwow....',
    '.wwwwww.....',
    '.wwwwwww....',
    '..sssssss...',
  ],
  boar: ['...s...s....', '..sssssss...', '.ssssssoss..', '.sssssssyw..', '..sssssss...', '..s.s.s.s...'],
  wolf: [
    '...s...s....',
    '...ss.ss....',
    '...swsws....',
    '.sssssoos...',
    '.ssssssww...',
    '..ssssss....',
    '..s..s......',
  ],
  bird: ['.....bbb....', '....bwoby...', '..bbbbb.....', '.bBBBBb.....', '...bbb......', '....ss......'],
  fish: ['....bbbbb...', 'b..bwwbbbb..', 'bbbwwbbbob..', 'bbbBBBBBBB..', 'b..BBBBBB...', '....BBBB....'],
  rain: [
    '...wwwww....',
    '..wwwwwww...',
    '.sswwwwsss..',
    '.sssssssss..',
    '............',
    '..b..b..b...',
    '.b..b..b....',
  ],
  storm: [
    '...sssss....',
    '..sssssss...',
    '.BBBBBBBBB..',
    '....yy......',
    '...yy..b....',
    '....yyb.....',
    '...yy.......',
    '...y........',
  ],
  sun: [
    '.....y......',
    '..y.....y...',
    '....yyy.....',
    '...yyyyy....',
    '.y.yyyyy.y..',
    '...yyyyy....',
    '....yyy.....',
    '..y.....y...',
    '.....y......',
  ],
  drought: [
    '........y...',
    '...G...yyy..',
    '.G.G....y...',
    '.GGG........',
    '...G..yyy...',
    '.yyyyyyyyyy.',
    '..sss.ssss..',
  ],
  germ: [
    '..g..g..g...',
    '...ggggg....',
    '..gGggGgg...',
    '.ggggggggg..',
    '..ggGgggg...',
    '...ggggg....',
    '..g..g..g...',
  ],
  clock: [
    '....yyy.....',
    '.....y......',
    '...wwwww....',
    '..wwwwwBw...',
    '.wwwwwBwww..',
    '.wwwwwBBww..',
    '.wwwwwwwww..',
    '..wwwwwww...',
    '...sssss....',
  ],
  pause: [
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
  ],
  play: [
    '...y........',
    '...yyy......',
    '...yyyyy....',
    '...yyyyyyy..',
    '...yyyyy....',
    '...yyy......',
    '...y........',
  ],
  fast: [
    '.y....y.....',
    '.yy...yy....',
    '.yyy..yyy...',
    '.yyyy.yyyy..',
    '.yyy..yyy...',
    '.yy...yy....',
    '.y....y.....',
  ],
  bolt: [
    '.....yyyy...',
    '....yyyy....',
    '...yyyy.....',
    '..yyyyyyy...',
    '.....yyy....',
    '....yyy.....',
    '...yy.......',
    '..y.........',
  ],
  turtle: ['...GGGGG....', '..GgGgGgG...', '..GGgGgGGgg.', '.gGgGgGgGgo.', '..GGGGGGG...', '..g.....g...'],
  chart: [
    '.........yy.',
    '.........yy.',
    '......gg.yy.',
    '......gg.yy.',
    '...rr.gg.yy.',
    '...rr.gg.yy.',
    '...rr.gg.yy.',
    '.ssssssssss.',
  ],
  book: [
    '..RRRRRRRR..',
    '..RRwwwwwR..',
    '..RRwssswR..',
    '..RRwwwwwR..',
    '..RRwssswR..',
    '..RRwwwwwR..',
    '..RRwwwwwR..',
    '..RRyyyyyR..',
    '..RRRRRRRR..',
  ],
  gear: [
    '.....ss.....',
    '..s.ssss.s..',
    '..ssssssss..',
    '...ss..ss...',
    '.sss....sss.',
    '.sss....sss.',
    '...ss..ss...',
    '..ssssssss..',
    '..s.ssss.s..',
    '.....ss.....',
  ],
  dots: ['.ww..ww..ww.', '.ww..ww..ww.'],
  crown: ['.y...y...y..', '.yy.yyy.yy..', '.yyyyyyyyy..', '.yryybyyry..', '.yyyyyyyyy..', '.RRRRRRRRR..'],
  moon: [
    '...wwww.....',
    '..www.......',
    '.www........',
    '.ww.........',
    '.ww.........',
    '.www........',
    '..www.......',
    '...wwww.....',
  ],
  expand: [
    '.www....www.',
    '.w........w.',
    '.w........w.',
    '............',
    '............',
    '.w........w.',
    '.w........w.',
    '.www....www.',
  ],
  panelLeft: [
    '.ssssssssss.',
    '.syys.....s.',
    '.syys.....s.',
    '.syys.....s.',
    '.syys.....s.',
    '.syys.....s.',
    '.syys.....s.',
    '.ssssssssss.',
  ],
  panelRight: [
    '.ssssssssss.',
    '.s.....syys.',
    '.s.....syys.',
    '.s.....syys.',
    '.s.....syys.',
    '.s.....syys.',
    '.s.....syys.',
    '.ssssssssss.',
  ],
  bloom: [
    '.....g......',
    '..g.ggg.g...',
    '..ggyyygg...',
    '.gyybbbyyg..',
    'ggybbbbbygg.',
    '.gyybbbyyg..',
    '..ggyyygg...',
    '..g.ggg.g...',
    '.....g......',
  ],
  poison: [
    '....ss......',
    '....ww......',
    '....ww......',
    '...wggw.....',
    '..wgGggw....',
    '.wggoogGw...',
    '.wgGoogGw...',
    '.wggGggGw...',
    '..wwwwww....',
  ],
  meteor: [
    '.........yy.',
    '........yy..',
    '.......yy...',
    '....rry.....',
    '...rRRrr....',
    '..rRssRr....',
    '..rRssRr....',
    '...rRRr.....',
    '....rr......',
  ],
  sparkle: [
    '.....y......',
    '.....y......',
    '..y.yyy.y...',
    '...yywyy....',
    'yyyywwwyyyy.',
    '...yywyy....',
    '..y.yyy.y...',
    '.....y......',
    '.....y......',
  ],
  bulb: [
    '....yyy.....',
    '...yywyy....',
    '..yywyyyy...',
    '..yyyyyyy...',
    '..yyyyyyy...',
    '...yyyyy....',
    '....sss.....',
    '....sss.....',
    '.....s......',
  ],
  dove: [
    '........ww..',
    '.......wwow.',
    '.ww...wwwwy.',
    'wwwww.www...',
    '.wwwwwwww...',
    '..wwwwwww...',
    '....wwww....',
    '.....s.s....',
  ],
  quake: [
    '..ss........',
    '..sss....ss.',
    '...ss...sss.',
    '....ss.sss..',
    '.....sss....',
    '....ss.ss...',
    '...ss...ss..',
    'ggsgggggsgg.',
    'GGGGGGGGGGG.',
  ],
  bear: [
    '.........RR.',
    '..RRRRRRRRR.',
    '.RRRRRRRRRso',
    '.RRRRRRRRRss',
    '.RRRRRRRRRR.',
    '..RRRRRRRR..',
    '..RR.RR.RR..',
    '..RR....RR..',
  ],
  sheep: [
    '..swwswws...',
    '.wwwwwwwwoo.',
    'swwwwwwwwowo',
    'wwwwwwwwwoo.',
    '.wswwwsww...',
    '..o..o.o....',
    '..o..o.o....',
  ],
  cow: [
    '.........s.s',
    '.wwwwwwwwooo',
    'wooowwwowooo',
    'wooowwwwwppp',
    'wwwwwoowww..',
    '.wwwwoowww..',
    '.o..o..o.o..',
    '.o..o..o.o..',
  ],
  horse: [
    '.........RR.',
    '........oRRR',
    '.......oRRoR',
    'o.RRRRRRRR..',
    'oRRRRRRRRR..',
    '.RRRRRRRR...',
    '.R.R...R.R..',
    '.R.R...R.R..',
    '.o.o...o.o..',
  ],
  chicken: [
    '......rr....',
    '.....www....',
    '.....wowy...',
    '..wwwwww....',
    '.wwwwwww....',
    '..wwwww.....',
    '...y.y......',
  ],
  search: [
    '...wwww.....',
    '..w....w....',
    '.w..bb..w...',
    '.w.b....w...',
    '.w......w...',
    '..w....w....',
    '...wwwws....',
    '.......sss..',
    '........sss.',
    '.........ss.',
  ],
  save: [
    '.BBBBBBBBB..',
    '.BwwwwwwoB..',
    '.BwwwwwwoB..',
    '.BwwwwwwwB..',
    '.BBBBBBBBB..',
    '.BBsssssBB..',
    '.BBsoossBB..',
    '.BBsoossBB..',
    '.BBBBBBBBB..',
  ],
  pill: [
    '.......ooo..',
    '......orrro.',
    '.....orrrro.',
    '....owrrro..',
    '...owwwoo...',
    '..owwwwo....',
    '.owwwwo.....',
    '.owwwo......',
    '..ooo.......',
  ],
  wheat: [
    '....y.y.y...',
    '...yy.y.yy..',
    '....yyyyy...',
    '...yy.y.yy..',
    '....yyyyy...',
    '.....yyy....',
    '......s.....',
    '......s.....',
    '.....s.s....',
    '....s...s...',
  ],
  thaw: [
    '......b.....',
    '.....bBb....',
    '......b.....',
    '....g.......',
    '...gGg......',
    '....G.......',
    'RsRsGsRsRsRs',
    'sRssRssRssRs',
    'ssssssssssss',
  ],
  village: [
    '..r.....r...',
    '.rrr...rrr..',
    'rrrrr.rrrrr.',
    '.wBw...wBw..',
    '.www.r.www..',
    '....rrr.....',
    '...rrrrr....',
    '....wBw.....',
    '....www.....',
  ],
  plea: [
    '..wwwwwwww..',
    '.wwwwrrwwww.',
    '.wwwwrrwwww.',
    '.wwwwrrwwww.',
    '.wwwwwwwwww.',
    '.wwwwrrwwww.',
    '..wwwwwwww..',
    '...ww.......',
    '..w.........',
  ],
  blossom: [
    '...p...y....',
    '..ppp.yyy...',
    '...p...y.p..',
    '...g...g.ppp',
    '..gG..gGg.p.',
    '...G...G..g.',
    '...G...G..G.',
    'gggGgggGggGg',
  ],
  seedling: [
    '............',
    '..g...g...g.',
    '.gGg.gGg.gGg',
    '..G...G...G.',
    'ssssssssssss',
    'RRRRRRRRRRRR',
    'ssssssssssss',
    'RRRRRRRRRRRR',
  ],
  sapling: [
    '.....gg.....',
    '....gGgg....',
    '...gGggGg...',
    '....gggg....',
    '.....s......',
    '.....s......',
    '....sss.....',
    '...oooooo...',
  ],
  fruittree: [
    '....gggg....',
    '..ggrgggGg..',
    '.gGgggggrgg.',
    '.ggrgGgggGg.',
    '..gggggrgg..',
    '...gggggg...',
    '.....ss.....',
    '.....ss.....',
    '....ssss....',
  ],
  sword: [
    '.........ww.',
    '........wwo.',
    '.......wwo..',
    '......wwo...',
    '.....wwo....',
    '..y.wwo.....',
    '...yyo......',
    '...sy.......',
    '..s..y......',
    '.s..........',
  ],
  gift: [
    '...rr.rr....',
    '....rrr.....',
    '.yyyyryyyy..',
    '.yyyyryyyy..',
    '.rrrrrrrrr..',
    '.yyyyryyyy..',
    '.yyyyryyyy..',
    '.yyyyryyyy..',
    '.yyyyryyyy..',
  ],
  bucket: [
    '...sss......',
    '..s...s.....',
    '.ssssssss...',
    '.sbbbbbbs...',
    '.sbbbbbbs...',
    '..sbbbbs....',
    '..sbbbbs....',
    '...ssss.....',
    '.b.....b....',
    'b..b.b..b...',
  ],
  shield: [
    '.bbbbbbbbb..',
    '.bwwwwwwwb..',
    '.bwwyywwwb..',
    '.bwyyyywwb..',
    '.bwwyywwwb..',
    '..bwwwwwb...',
    '...bwwwb....',
    '....bwb.....',
    '.....b......',
  ],
  ward: [
    '...yyyyyy...',
    '..y......y..',
    '.y...r....y.',
    'y...rrr....y',
    'y..rrrrr...y',
    'y..wwyww...y',
    'y..wwBww...y',
    'y..wwRww...y',
    'gggggggggggg',
    'GGGGGGGGGGGG',
  ],
  angry: [
    '...rrrrr....',
    '..rrrrrrr...',
    '.ro.rrr.or..',
    '.rrorrrorr..',
    '.rrrrrrrrr..',
    '.rrrooorrr..',
    '.rrorrrorr..',
    '..rrrrrrr...',
    '...rrrrr....',
  ],
  thunder: [
    '...www......',
    '..wwwww.ww..',
    '.wwwwwwwwww.',
    '.ssssssssss.',
    '.....yy.....',
    '....yy......',
    '...yyyy.....',
    '.....yy.....',
    '....yy......',
    '...y........',
  ],
  wilt: [
    '.......RR...',
    '......RRpR..',
    '......RRR...',
    '.....s......',
    '....s.......',
    '...s..s.....',
    '...s.s......',
    '...ss.......',
    '...s........',
    '..sss.......',
  ],
  wave: [
    '......bbbb..',
    '....bbwwwbb.',
    '...bbw...wb.',
    '..bbw.......',
    '.bbbb..b....',
    'bbbbbbbbb.b.',
    'BBBBBBBBBBBB',
    'BBBBBBBBBBBB',
  ],
  blizzard: [
    '...www......',
    '..wwwww.ww..',
    '.wwwwwwwwww.',
    '.ssssssssss.',
    '..w...w...w.',
    '.www.www.www',
    '..w...w...w.',
    '....w...w...',
    '...www.www..',
    '....w...w...',
  ],
  zombie: [
    '..gggg......',
    '..gogg......',
    '..gggg......',
    '...gg.......',
    '..BBBBggggg.',
    '..BBBB......',
    '..BBBB......',
    '..ss.ss.....',
    '..ss.ss.....',
    '..oo.oo.....',
  ],
  demon: [
    '.r......r...',
    '.rr....rr...',
    '..rrrrrr....',
    '..ryrryr....',
    '..rrrrrr....',
    '..rwwwwr....',
    '...rrrr.....',
    '..RRRRRR....',
    '.R.RRRR.R...',
    '...R..R.....',
  ],
  dragon: [
    '..........G.',
    '.G.......GGo',
    'GGG.....GGGG',
    '.GGGG..GGG..',
    '..GGGGGGG...',
    '...GgggGG...',
    '..GGGGGGGG..',
    '.G...GG..G..',
    '....G..G....',
  ],
  alien: [
    '...gggggg...',
    '..gggggggg..',
    '..googgoog..',
    '..googgoog..',
    '...gggggg...',
    '....gggg....',
    '.....gg.....',
    '...ssssss...',
    '..s.ssss.s..',
    '....s..s....',
  ],
  ufo: [
    '.....bb.....',
    '....bwwb....',
    '...bbbbbb...',
    '.ssssssssss.',
    'ssyssyssyss.',
    '.ssssssssss.',
    '...y....y...',
    '..y......y..',
  ],
  b_meadow: [
    '............',
    '..p.....y...',
    '.pyp...yry..',
    '..p.y...y...',
    '..g.g.g.g.g.',
    '.ggGggGgggg.',
    'GgGgGgGgGgGG',
    'GGGGGGGGGGGG',
  ],
  b_oak: [
    '....gggg....',
    '..gggGgggg..',
    '.ggGgggGggg.',
    '.gggggGgggg.',
    '..ggGgggGg..',
    '...gggggg...',
    '.....ss.....',
    '.....ss.....',
    '....ssss....',
  ],
  b_palm: [
    '..gg....gg..',
    '.ggGg..gGgg.',
    'g...gggg...g',
    '....gGGg....',
    '.....ss.....',
    '.....s......',
    '......s.....',
    '......s.....',
    '.....sss....',
  ],
  b_acacia: [
    '..GGGGGGGG..',
    '.GgggggggggG',
    '..GGGGGGGG..',
    '.....s......',
    '......s.....',
    '....s.s.....',
    '.....s......',
    '.....s......',
    '....sss.....',
  ],
  b_cactus: [
    '.....g......',
    '.....gG.....',
    '.g...gG.....',
    '.gG..gG..g..',
    '.gGggGG..gG.',
    '..GGggG.ggG.',
    '.....gGGG...',
    '.....gG.....',
    '.yyyyyyyyyy.',
  ],
  b_mesa: [
    '............',
    '...RRRRR....',
    '...rrrrR....',
    '...rrrrR....',
    '..rrrrrrR...',
    '..rrrrrrRR..',
    '.rrrrrrrrRR.',
    'yyyyyyyyyyyy',
  ],
  b_reeds: [
    '..s....s....',
    '..s.s..s.s..',
    '.gs.s.gs.s..',
    '.g.gs.g..sg.',
    '.g.g..g.g.g.',
    'bbgbgbbgbgbb',
    'bbbbbbbbbbbb',
  ],
  b_tundra: [
    '............',
    '.....ww.....',
    '...wwwwww...',
    '..wsswwwsw..',
    '.wwwwwwwwww.',
    'wwsswwwwssww',
    'wwwwwwwwwwww',
  ],
  b_pine: [
    '.....w......',
    '....wGw.....',
    '...wGGGw....',
    '....GGG.....',
    '..wGGGGGw...',
    '...GGGGG....',
    '.wGGGGGGGw..',
    '.....s......',
    '.....s......',
  ],
  b_hearts: [
    '.rr.rr......',
    'rrrrrrr.....',
    'rrrrrrr.rr.r',
    '.rrrrrrrrrrr',
    '..rrrr.rrrrr',
    '...rr...rrr.',
    '.........r..',
  ],
  b_dog: [
    '.........ss.',
    '........ssso',
    '.sssssssssss',
    'ssssssssss..',
    '.ssssssss...',
    '.s.s...s.s..',
    '.s.s...s.s..',
  ],
  b_volcano: [
    '.....rr.....',
    '....rRRr....',
    '....syys....',
    '...ssyyss...',
    '..sssssss...',
    '.sssssssss..',
    'sssssssssss.',
    'ssssssssssss',
  ],
  b_starfall: [
    'y.........y.',
    '.y.......y..',
    '..yy....y...',
    '...yyy.y....',
    '....yyy.....',
    '.....rr.....',
    '....rrrr....',
    '.....rr.....',
  ],
  v_hourglass: [
    '.ssssssss...',
    '..yyyyyy....',
    '...yyyy.....',
    '....yy......',
    '....yy......',
    '...y..y.....',
    '..yyyyyy....',
    '.ssssssss...',
  ],
  v_warning: [
    '.....rr.....',
    '....rwwr....',
    '....rwwr....',
    '...rrwwrr...',
    '...rrwwrr...',
    '..rrrrrrrr..',
    '..rrrwwrrr..',
    '.rrrrrrrrrr.',
  ],
  v_tag: ['..ssssssss..', '.swwwwwwwws.', 'swwoowowwws.', 'swwwwwwwwws.', '.swwwwwwwws.', '..ssssssss..'],
  v_bubble: [
    '...wwwwww...',
    '..wwwwwwww..',
    '.wwowwowoww.',
    '.wwwwwwwwww.',
    '..wwwwwwww..',
    '...wwwww....',
    '..ww........',
    '.w..........',
  ],
  v_paw: [
    '..s....s....',
    '.sss..sss...',
    '..s....s....',
    's...ss...s..',
    'ss.ssss.ss..',
    '...ssssss...',
    '....ssss....',
  ],
  v_grid: [
    's...s...s...',
    'ssssssssssss',
    's...s...s...',
    's...s...s...',
    'ssssssssssss',
    's...s...s...',
    's...s...s...',
    'ssssssssssss',
  ],
  v_eye: ['............', '...wwwwww...', '.wwwbbbbwww.', 'wwwbbobbbwww', '.wwwbbbbwww.', '...wwwwww...'],
} satisfies Record<string, string[]>

const icons: Record<string, keyof typeof sprites> = {
  '🚶': 'person',
  '🏠': 'house',
  '🛖': 'house',
  '⛰️': 'mountain',
  '🍎': 'apple',
  '🗺️': 'map',
  '🖱️': 'cursor',
  '✚': 'plus',
  '👥': 'tribe',
  '💚': 'heart',
  '❤️': 'heart',
  '💀': 'skull',
  '🔥': 'fire',
  '🟩': 'grass',
  '🟦': 'water',
  '🪨': 'rock',
  '🟨': 'sand',
  '❄️': 'snow',
  '💧': 'drop',
  '⬡': 'border',
  '🏘️': 'village',
  '⚔️': 'swords',
  '〰️': 'route',
  '🧭': 'compass',
  '🦌': 'deer',
  '🐇': 'rabbit',
  '🐗': 'boar',
  '🐺': 'wolf',
  '🐦': 'bird',
  '🐟': 'fish',
  '🐻': 'bear',
  '🐑': 'sheep',
  '🐄': 'cow',
  '🐎': 'horse',
  '🐔': 'chicken',
  '🌧️': 'rain',
  '⛈️': 'storm',
  '☀️': 'sun',
  '🏜️': 'drought',
  '🌦️': 'thaw',
  '🦠': 'germ',
  '⏱️': 'clock',
  '⏸️': 'pause',
  '▶️': 'play',
  '🐢': 'turtle',
  '⏩': 'fast',
  '⏭️': 'fast',
  '⚡': 'bolt',
  '🔍': 'search',
  '💾': 'save',
  '📊': 'chart',
  '📖': 'book',
  '⚙️': 'gear',
  '⋯': 'dots',
  '👑': 'crown',
  '🌙': 'moon',
  '⛶': 'expand',
  '◧': 'panelLeft',
  '◨': 'panelRight',
  '🌼': 'bloom',
  '🧪': 'poison',
  '☄️': 'meteor',
  '✨': 'sparkle',
  '💡': 'bulb',
  '🕊️': 'dove',
  '〽️': 'quake',
  '💊': 'pill',
  '🌾': 'wheat',
  '🌿': 'seedling',
  '🌸': 'blossom',
  '🙏': 'plea',
  '🪴': 'sapling',
  '🍐': 'fruittree',
  '🗡️': 'sword',
  '🎁': 'gift',
  '🪣': 'bucket',
  '🛡️': 'shield',
  '🔰': 'ward',
  '😡': 'angry',
  '🌩️': 'thunder',
  '🥀': 'wilt',
  '🌊': 'wave',
  '🌨️': 'blizzard',
  '🧟': 'zombie',
  '👹': 'demon',
  '🐉': 'dragon',
  '👽': 'alien',
  '🛸': 'ufo',
  '🌱': 'b_meadow',
  '🌳': 'b_oak',
  '🌴': 'b_palm',
  '🦒': 'b_acacia',
  '🌵': 'b_cactus',
  '🟥': 'b_mesa',
  '🪷': 'b_reeds',
  '🧊': 'b_tundra',
  '🌲': 'b_pine',
  '💞': 'b_hearts',
  '🦮': 'b_dog',
  '🌋': 'b_volcano',
  '🌠': 'b_starfall',
  '⏳': 'v_hourglass',
  '⚠️': 'v_warning',
  '🏷️': 'v_tag',
  '💭': 'v_bubble',
  '🐾': 'v_paw',
  '#️⃣': 'v_grid',
  '👁️': 'v_eye',
}

const viewBoxes = new Map<string, string>()

/**
 * Sprites are drawn on a 12x12 grid but rarely fill it evenly, so the view
 * box is centred on each sprite's painted pixels. That keeps every sprite
 * optically centred in its tile without hand-tuning the artwork.
 */
function centredViewBox(name: string, rows: readonly string[]): string {
  const cached = viewBoxes.get(name)
  if (cached) return cached
  let minX = 12
  let maxX = -1
  let minY = rows.length
  let maxY = -1
  rows.forEach((row, y) => {
    ;[...row].forEach((pixel, x) => {
      if (pixel === '.') return
      minX = Math.min(minX, x)
      maxX = Math.max(maxX, x)
      minY = Math.min(minY, y)
      maxY = Math.max(maxY, y)
    })
  })
  const box = maxX < 0 ? '0 0 12 12' : `${(minX + maxX + 1) / 2 - 6} ${(minY + maxY + 1) / 2 - 6} 12 12`
  viewBoxes.set(name, box)
  return box
}

export function ToolSprite({ icon, size = 24 }: { icon: string; size?: number }) {
  const name = icons[icon] ?? 'cursor'
  const rows = sprites[name]
  return (
    <svg
      width={size}
      height={size}
      viewBox={centredViewBox(name, rows)}
      shapeRendering="crispEdges"
      aria-hidden="true"
      focusable="false"
      style={{ display: 'block', flexShrink: 0 }}
    >
      {rows.flatMap((row, y) =>
        [...row].flatMap((pixel, x) =>
          pixel === '.'
            ? []
            : [<rect key={`${x}-${y}`} x={x} y={y} width="1" height="1" fill={palette[pixel]} />],
        ),
      )}
    </svg>
  )
}
