//! Discoveries from the first foraging through the classical age.

use super::*;

pub(super) const ANCIENT: &[TechNode] = &[
    TechNode {
        name: "foraging",
        era: Era::PreStone,
        prerequisites: &[],
        unlocks: &["basket_weaving"],
        discovery_rate: 8.0,
    },
    TechNode {
        name: "fire",
        era: Era::Stone,
        prerequisites: &[],
        unlocks: &["cooking", "torch"],
        discovery_rate: 6.0,
    },
    TechNode {
        name: "stone_tools",
        era: Era::Stone,
        prerequisites: &["fire"],
        unlocks: &["tool_making"],
        discovery_rate: 5.0,
    },
    TechNode {
        name: "shelter",
        era: Era::Stone,
        prerequisites: &["foraging"],
        unlocks: &["masonry"],
        discovery_rate: 5.0,
    },
    TechNode {
        name: "language",
        era: Era::Stone,
        prerequisites: &["foraging"],
        unlocks: &["writing"],
        discovery_rate: 4.5,
    },
    TechNode {
        name: "tool_making",
        era: Era::Stone,
        prerequisites: &["stone_tools"],
        unlocks: &["fishing", "hunting"],
        discovery_rate: 4.0,
    },
    TechNode {
        name: "fishing",
        era: Era::Stone,
        prerequisites: &["tool_making"],
        unlocks: &[],
        discovery_rate: 3.5,
    },
    TechNode {
        name: "hunting",
        era: Era::Stone,
        prerequisites: &["tool_making"],
        unlocks: &["leather"],
        discovery_rate: 4.5,
    },
    TechNode {
        name: "basket_weaving",
        era: Era::Stone,
        prerequisites: &["foraging"],
        unlocks: &["weaving"],
        discovery_rate: 4.0,
    },
    TechNode {
        name: "leather",
        era: Era::Stone,
        prerequisites: &["hunting"],
        unlocks: &[],
        discovery_rate: 3.0,
    },
    TechNode {
        name: "body_paint",
        era: Era::Stone,
        prerequisites: &["foraging"],
        unlocks: &["dye"],
        discovery_rate: 2.5,
    },
    TechNode {
        name: "smelting",
        era: Era::Bronze,
        prerequisites: &["fire", "stone_tools"],
        unlocks: &["ironworking"],
        discovery_rate: 2.5,
    },
    TechNode {
        name: "pottery",
        era: Era::Bronze,
        prerequisites: &["fire"],
        unlocks: &["ceramics"],
        discovery_rate: 3.0,
    },
    TechNode {
        name: "agriculture",
        era: Era::Bronze,
        prerequisites: &["foraging"],
        unlocks: &["plowing", "brewing"],
        discovery_rate: 4.0,
    },
    TechNode {
        name: "animal_domestication",
        era: Era::Bronze,
        prerequisites: &["hunting"],
        unlocks: &["plowing"],
        discovery_rate: 2.5,
    },
    TechNode {
        name: "weaving",
        era: Era::Bronze,
        prerequisites: &["basket_weaving"],
        unlocks: &["dye"],
        discovery_rate: 4.0,
    },
    TechNode {
        name: "wheel",
        era: Era::Bronze,
        prerequisites: &["tool_making"],
        unlocks: &["plowing"],
        discovery_rate: 2.0,
    },
    TechNode {
        name: "sail",
        era: Era::Bronze,
        prerequisites: &["weaving"],
        unlocks: &["navigation"],
        discovery_rate: 1.8,
    },
    TechNode {
        name: "plowing",
        era: Era::Bronze,
        prerequisites: &["agriculture", "animal_domestication"],
        unlocks: &[],
        discovery_rate: 2.0,
    },
    TechNode {
        name: "dye",
        era: Era::Bronze,
        prerequisites: &["weaving"],
        unlocks: &[],
        discovery_rate: 2.0,
    },
    TechNode {
        name: "salt",
        era: Era::Bronze,
        prerequisites: &["foraging"],
        unlocks: &[],
        discovery_rate: 2.0,
    },
    TechNode {
        name: "candle",
        era: Era::Bronze,
        prerequisites: &["fire"],
        unlocks: &[],
        discovery_rate: 2.0,
    },
    TechNode {
        name: "ceramics",
        era: Era::Bronze,
        prerequisites: &["pottery"],
        unlocks: &[],
        discovery_rate: 1.8,
    },
    TechNode {
        name: "brewing",
        era: Era::Bronze,
        prerequisites: &["agriculture"],
        unlocks: &[],
        discovery_rate: 3.5,
    },
    TechNode {
        name: "navigation",
        era: Era::Bronze,
        prerequisites: &["sail"],
        unlocks: &["cartography"],
        discovery_rate: 1.5,
    },
    TechNode {
        name: "ironworking",
        era: Era::Iron,
        prerequisites: &["smelting"],
        unlocks: &["masonry"],
        discovery_rate: 2.0,
    },
    TechNode {
        name: "writing",
        era: Era::Iron,
        prerequisites: &["language"],
        unlocks: &["alphabet"],
        discovery_rate: 3.5,
    },
    TechNode {
        name: "alphabet",
        era: Era::Iron,
        prerequisites: &["writing"],
        unlocks: &["library_concept"],
        discovery_rate: 1.8,
    },
    TechNode {
        name: "glass",
        era: Era::Iron,
        prerequisites: &["smelting"],
        unlocks: &["telescope"],
        discovery_rate: 1.6,
    },
    TechNode {
        name: "masonry",
        era: Era::Iron,
        prerequisites: &["shelter", "ironworking"],
        unlocks: &["arch", "aqueduct"],
        discovery_rate: 1.8,
    },
    TechNode {
        name: "road_building",
        era: Era::Iron,
        prerequisites: &["masonry", "wheel"],
        unlocks: &[],
        discovery_rate: 1.5,
    },
    TechNode {
        name: "calendar",
        era: Era::Iron,
        prerequisites: &["writing", "astronomy"],
        unlocks: &[],
        discovery_rate: 1.4,
    },
    TechNode {
        name: "currency",
        era: Era::Iron,
        prerequisites: &["writing"],
        unlocks: &["double_entry_bookkeeping"],
        discovery_rate: 1.6,
    },
    TechNode {
        name: "mathematics",
        era: Era::Iron,
        prerequisites: &["writing"],
        unlocks: &["geometry", "physics"],
        discovery_rate: 1.8,
    },
    TechNode {
        name: "philosophy",
        era: Era::Iron,
        prerequisites: &["writing"],
        unlocks: &["democracy"],
        discovery_rate: 1.5,
    },
    TechNode {
        name: "astronomy",
        era: Era::Iron,
        prerequisites: &["mathematics"],
        unlocks: &["astronomy_helio"],
        discovery_rate: 1.4,
    },
    TechNode {
        name: "engineering",
        era: Era::Iron,
        prerequisites: &["mathematics", "masonry"],
        unlocks: &["aqueduct", "dome"],
        discovery_rate: 1.4,
    },
    TechNode {
        name: "irrigation",
        era: Era::Iron,
        prerequisites: &["agriculture", "masonry"],
        unlocks: &[],
        discovery_rate: 1.6,
    },
    TechNode {
        name: "aqueduct",
        era: Era::Iron,
        prerequisites: &["engineering"],
        unlocks: &["plumbing"],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "plumbing",
        era: Era::Iron,
        prerequisites: &["aqueduct"],
        unlocks: &[],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "mosaic",
        era: Era::Iron,
        prerequisites: &["ceramics"],
        unlocks: &[],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "democracy",
        era: Era::Classical,
        prerequisites: &["philosophy"],
        unlocks: &["law_code"],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "theater",
        era: Era::Classical,
        prerequisites: &["writing"],
        unlocks: &["opera"],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "library_concept",
        era: Era::Classical,
        prerequisites: &["alphabet"],
        unlocks: &["university_concept"],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "surgery",
        era: Era::Classical,
        prerequisites: &["anatomy"],
        unlocks: &["anesthesia"],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "anatomy",
        era: Era::Classical,
        prerequisites: &["philosophy"],
        unlocks: &["anatomy_modern"],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "geometry",
        era: Era::Classical,
        prerequisites: &["mathematics"],
        unlocks: &["perspective_drawing"],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "physics",
        era: Era::Classical,
        prerequisites: &["mathematics"],
        unlocks: &["chemistry"],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "chemistry",
        era: Era::Classical,
        prerequisites: &["physics"],
        unlocks: &["alchemy"],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "law_code",
        era: Era::Classical,
        prerequisites: &["writing", "democracy"],
        unlocks: &[],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "columns",
        era: Era::Classical,
        prerequisites: &["masonry"],
        unlocks: &[],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "dome",
        era: Era::Classical,
        prerequisites: &["arch"],
        unlocks: &[],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "arch",
        era: Era::Classical,
        prerequisites: &["masonry"],
        unlocks: &["dome"],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "cement",
        era: Era::Classical,
        prerequisites: &["masonry"],
        unlocks: &[],
        discovery_rate: 1.0,
    },
];
