//! Side branches that fill out the early and middle ages: medicine, music and
//! art, crafts, learning, and a few later materials and networks.

use super::*;

pub(super) const BRANCHES: &[TechNode] = &[
    TechNode {
        name: "herbalism",
        era: Era::Stone,
        prerequisites: &["foraging"],
        unlocks: &["medicine_lore", "poultice"],
        discovery_rate: 4.5,
    },
    TechNode {
        name: "medicine_lore",
        era: Era::Stone,
        prerequisites: &["herbalism"],
        unlocks: &["midwifery"],
        discovery_rate: 3.5,
    },
    TechNode {
        name: "poultice",
        era: Era::Stone,
        prerequisites: &["herbalism"],
        unlocks: &[],
        discovery_rate: 3.5,
    },
    TechNode {
        name: "midwifery",
        era: Era::Stone,
        prerequisites: &["medicine_lore"],
        unlocks: &[],
        discovery_rate: 3.0,
    },
    TechNode {
        name: "drumming",
        era: Era::Stone,
        prerequisites: &["foraging"],
        unlocks: &["signal_drums", "ritual_dance"],
        discovery_rate: 4.0,
    },
    TechNode {
        name: "signal_drums",
        era: Era::Stone,
        prerequisites: &["drumming"],
        unlocks: &[],
        discovery_rate: 3.0,
    },
    TechNode {
        name: "ritual_dance",
        era: Era::Stone,
        prerequisites: &["drumming"],
        unlocks: &[],
        discovery_rate: 3.0,
    },
    TechNode {
        name: "cave_painting",
        era: Era::Stone,
        prerequisites: &["fire", "language"],
        unlocks: &["pigment_making"],
        discovery_rate: 3.0,
    },
    TechNode {
        name: "pigment_making",
        era: Era::Stone,
        prerequisites: &["cave_painting"],
        unlocks: &[],
        discovery_rate: 2.5,
    },
    TechNode {
        name: "smoke_signals",
        era: Era::Stone,
        prerequisites: &["fire"],
        unlocks: &[],
        discovery_rate: 3.0,
    },
    TechNode {
        name: "salt_harvesting",
        era: Era::Stone,
        prerequisites: &["foraging"],
        unlocks: &["food_preservation"],
        discovery_rate: 2.5,
    },
    TechNode {
        name: "food_preservation",
        era: Era::Stone,
        prerequisites: &["salt_harvesting", "fire"],
        unlocks: &[],
        discovery_rate: 2.0,
    },
    TechNode {
        name: "animal_hides",
        era: Era::Stone,
        prerequisites: &["hunting"],
        unlocks: &["leatherwork"],
        discovery_rate: 3.0,
    },
    TechNode {
        name: "leatherwork",
        era: Era::Stone,
        prerequisites: &["animal_hides"],
        unlocks: &[],
        discovery_rate: 2.5,
    },
    TechNode {
        name: "raft_building",
        era: Era::Stone,
        prerequisites: &["tool_making", "fishing"],
        unlocks: &["river_travel"],
        discovery_rate: 2.5,
    },
    TechNode {
        name: "river_travel",
        era: Era::Stone,
        prerequisites: &["raft_building"],
        unlocks: &[],
        discovery_rate: 2.0,
    },
    TechNode {
        name: "beekeeping",
        era: Era::Bronze,
        prerequisites: &["foraging", "shelter"],
        unlocks: &["honey_brewing"],
        discovery_rate: 2.0,
    },
    TechNode {
        name: "honey_brewing",
        era: Era::Bronze,
        prerequisites: &["beekeeping"],
        unlocks: &[],
        discovery_rate: 1.8,
    },
    TechNode {
        name: "pottery_glaze",
        era: Era::Bronze,
        prerequisites: &["pottery"],
        unlocks: &[],
        discovery_rate: 1.8,
    },
    TechNode {
        name: "open_pit_mining",
        era: Era::Bronze,
        prerequisites: &["stone_tools"],
        unlocks: &["ore_smelting"],
        discovery_rate: 1.8,
    },
    TechNode {
        name: "ore_smelting",
        era: Era::Bronze,
        prerequisites: &["open_pit_mining", "fire"],
        unlocks: &[],
        discovery_rate: 1.6,
    },
    TechNode {
        name: "astronomy_basics",
        era: Era::Bronze,
        prerequisites: &["language"],
        unlocks: &["star_charts"],
        discovery_rate: 1.6,
    },
    TechNode {
        name: "star_charts",
        era: Era::Bronze,
        prerequisites: &["astronomy_basics"],
        unlocks: &[],
        discovery_rate: 1.4,
    },
    TechNode {
        name: "glassblowing",
        era: Era::Iron,
        prerequisites: &["ore_smelting"],
        unlocks: &[],
        discovery_rate: 1.4,
    },
    TechNode {
        name: "mathematics",
        era: Era::Iron,
        prerequisites: &["writing"],
        unlocks: &["geometry", "abacus"],
        discovery_rate: 1.4,
    },
    TechNode {
        name: "geometry",
        era: Era::Iron,
        prerequisites: &["mathematics"],
        unlocks: &[],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "abacus",
        era: Era::Iron,
        prerequisites: &["mathematics"],
        unlocks: &[],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "cartography",
        era: Era::Iron,
        prerequisites: &["writing", "geometry"],
        unlocks: &[],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "philosophy",
        era: Era::Classical,
        prerequisites: &["mathematics", "writing"],
        unlocks: &["ethics", "logic"],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "ethics",
        era: Era::Classical,
        prerequisites: &["philosophy"],
        unlocks: &[],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "logic",
        era: Era::Classical,
        prerequisites: &["philosophy"],
        unlocks: &[],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "theater",
        era: Era::Classical,
        prerequisites: &["language", "ritual_dance"],
        unlocks: &[],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "heraldry",
        era: Era::Medieval,
        prerequisites: &["writing"],
        unlocks: &[],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "alchemy",
        era: Era::Medieval,
        prerequisites: &["medicine_lore", "ore_smelting"],
        unlocks: &["distillation"],
        discovery_rate: 0.8,
    },
    TechNode {
        name: "distillation",
        era: Era::Medieval,
        prerequisites: &["alchemy"],
        unlocks: &[],
        discovery_rate: 0.7,
    },
    TechNode {
        name: "perspective_art",
        era: Era::Renaissance,
        prerequisites: &["geometry", "pigment_making"],
        unlocks: &[],
        discovery_rate: 0.7,
    },
    TechNode {
        name: "navigation_charts",
        era: Era::Renaissance,
        prerequisites: &["cartography", "star_charts"],
        unlocks: &[],
        discovery_rate: 0.7,
    },
    TechNode {
        name: "refrigeration",
        era: Era::Modern,
        prerequisites: &["electricity_generation"],
        unlocks: &[],
        discovery_rate: 0.5,
    },
    TechNode {
        name: "antibiotics",
        era: Era::Modern,
        prerequisites: &["chemistry", "medicine_lore"],
        unlocks: &[],
        discovery_rate: 0.5,
    },
    TechNode {
        name: "plastics",
        era: Era::Modern,
        prerequisites: &["chemistry"],
        unlocks: &[],
        discovery_rate: 0.5,
    },
    TechNode {
        name: "search_engine",
        era: Era::Information,
        prerequisites: &["internet"],
        unlocks: &[],
        discovery_rate: 0.4,
    },
    TechNode {
        name: "encryption",
        era: Era::Information,
        prerequisites: &["computer", "mathematics"],
        unlocks: &[],
        discovery_rate: 0.4,
    },
    TechNode {
        name: "social_network",
        era: Era::Information,
        prerequisites: &["internet"],
        unlocks: &[],
        discovery_rate: 0.4,
    },
    TechNode {
        name: "nuclear_power",
        era: Era::Atomic,
        prerequisites: &["chemistry", "electricity_generation"],
        unlocks: &[],
        discovery_rate: 0.3,
    },
    TechNode {
        name: "asteroid_mining",
        era: Era::Space,
        prerequisites: &["spaceflight", "open_pit_mining"],
        unlocks: &[],
        discovery_rate: 0.25,
    },
    TechNode {
        name: "terraforming_theory",
        era: Era::Space,
        prerequisites: &["spaceflight", "chemistry"],
        unlocks: &[],
        discovery_rate: 0.2,
    },
];
