//! Discoveries from the interstellar age through the final ages.

use super::*;

pub(super) const COSMIC: &[TechNode] = &[
    TechNode {
        name: "warp",
        era: Era::Interstellar,
        prerequisites: &["fusion_reactor", "quantum_compute"],
        unlocks: &["generation_ship"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "generation_ship",
        era: Era::Interstellar,
        prerequisites: &["space_elevator", "post_scarcity"],
        unlocks: &["exoplanet"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "exoplanet",
        era: Era::Interstellar,
        prerequisites: &["generation_ship"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "agi",
        era: Era::Singularity,
        prerequisites: &["AI", "consciousness_net"],
        unlocks: &["self_improvement"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "self_improvement",
        era: Era::Singularity,
        prerequisites: &["agi"],
        unlocks: &["transcend"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "transcend",
        era: Era::Singularity,
        prerequisites: &["self_improvement"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "dyson_swarm",
        era: Era::Galactic,
        prerequisites: &["space_elevator", "fusion_reactor"],
        unlocks: &["dyson_sphere"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "galactic_net",
        era: Era::Galactic,
        prerequisites: &["agi", "entanglement"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "kardashev2",
        era: Era::Galactic,
        prerequisites: &["dyson_swarm"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "dyson_sphere",
        era: Era::Dyson,
        prerequisites: &["dyson_swarm"],
        unlocks: &["stellar_engineering"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "stellar_engineering",
        era: Era::Dyson,
        prerequisites: &["dyson_sphere"],
        unlocks: &["megaswarm"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "megaswarm",
        era: Era::Dyson,
        prerequisites: &["stellar_engineering"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "stellar_harvest",
        era: Era::Kardashev2,
        prerequisites: &["dyson_sphere"],
        unlocks: &["planet_lift"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "planet_lift",
        era: Era::Kardashev2,
        prerequisites: &["stellar_harvest"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "galactic_coms",
        era: Era::Kardashev2,
        prerequisites: &["galactic_net"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "galactic_engine",
        era: Era::Kardashev3,
        prerequisites: &["stellar_harvest"],
        unlocks: &["star_forge"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "star_forge",
        era: Era::Kardashev3,
        prerequisites: &["galactic_engine"],
        unlocks: &["supercluster"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "supercluster",
        era: Era::Kardashev3,
        prerequisites: &["star_forge"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "star_lifting",
        era: Era::Stellar,
        prerequisites: &["star_forge"],
        unlocks: &["stellar_remix"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "stellar_remix",
        era: Era::Stellar,
        prerequisites: &["star_lifting"],
        unlocks: &["corona_mining"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "corona_mining",
        era: Era::Stellar,
        prerequisites: &["stellar_remix"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "nebula_weave",
        era: Era::Nebular,
        prerequisites: &["star_lifting"],
        unlocks: &["dustfold"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "dustfold",
        era: Era::Nebular,
        prerequisites: &["nebula_weave"],
        unlocks: &["gas_husbandry"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "gas_husbandry",
        era: Era::Nebular,
        prerequisites: &["dustfold"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "vacuum_engineering",
        era: Era::Universal,
        prerequisites: &["nebula_weave"],
        unlocks: &["cosmic_strings"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "cosmic_strings",
        era: Era::Universal,
        prerequisites: &["vacuum_engineering"],
        unlocks: &["universal_constant"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "universal_constant",
        era: Era::Universal,
        prerequisites: &["cosmic_strings"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "branch_travel",
        era: Era::Multiverse,
        prerequisites: &["universal_constant"],
        unlocks: &["timelines"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "timelines",
        era: Era::Multiverse,
        prerequisites: &["branch_travel"],
        unlocks: &["parallel_consensus"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "parallel_consensus",
        era: Era::Multiverse,
        prerequisites: &["timelines"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "ascension",
        era: Era::Transcendent,
        prerequisites: &["parallel_consensus"],
        unlocks: &["boundary_break"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "boundary_break",
        era: Era::Transcendent,
        prerequisites: &["ascension"],
        unlocks: &["unbeing"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "unbeing",
        era: Era::Transcendent,
        prerequisites: &["boundary_break"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "deep_lore",
        era: Era::Eldritch,
        prerequisites: &["unbeing"],
        unlocks: &["outer_pact"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "outer_pact",
        era: Era::Eldritch,
        prerequisites: &["deep_lore"],
        unlocks: &["abyssal_geometry"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "abyssal_geometry",
        era: Era::Eldritch,
        prerequisites: &["outer_pact"],
        unlocks: &["void_walking"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "void_walking",
        era: Era::Voidborn,
        prerequisites: &["abyssal_geometry"],
        unlocks: &["hollow_stars"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "hollow_stars",
        era: Era::Voidborn,
        prerequisites: &["void_walking"],
        unlocks: &["null_tongue"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "null_tongue",
        era: Era::Voidborn,
        prerequisites: &["hollow_stars"],
        unlocks: &["time_loom"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "time_loom",
        era: Era::Chronal,
        prerequisites: &["null_tongue"],
        unlocks: &["causal_weaving"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "causal_weaving",
        era: Era::Chronal,
        prerequisites: &["time_loom"],
        unlocks: &["paradox_engine"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "paradox_engine",
        era: Era::Chronal,
        prerequisites: &["causal_weaving"],
        unlocks: &["akashic_index"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "akashic_index",
        era: Era::Akashic,
        prerequisites: &["paradox_engine"],
        unlocks: &["memory_of_stars"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "memory_of_stars",
        era: Era::Akashic,
        prerequisites: &["akashic_index"],
        unlocks: &["living_archive"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "living_archive",
        era: Era::Akashic,
        prerequisites: &["memory_of_stars"],
        unlocks: &["entropy_mastery"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "entropy_mastery",
        era: Era::Entropic,
        prerequisites: &["living_archive"],
        unlocks: &["heat_death_ward"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "heat_death_ward",
        era: Era::Entropic,
        prerequisites: &["entropy_mastery"],
        unlocks: &["order_from_decay"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "order_from_decay",
        era: Era::Entropic,
        prerequisites: &["heat_death_ward"],
        unlocks: &["dream_architecture"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "dream_architecture",
        era: Era::Oneiric,
        prerequisites: &["order_from_decay"],
        unlocks: &["lucid_cosmos"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "lucid_cosmos",
        era: Era::Oneiric,
        prerequisites: &["dream_architecture"],
        unlocks: &["sleeper_awakening"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "sleeper_awakening",
        era: Era::Oneiric,
        prerequisites: &["lucid_cosmos"],
        unlocks: &["myth_forging"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "myth_forging",
        era: Era::Mythic,
        prerequisites: &["sleeper_awakening"],
        unlocks: &["belief_engine"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "belief_engine",
        era: Era::Mythic,
        prerequisites: &["myth_forging"],
        unlocks: &["living_legends"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "living_legends",
        era: Era::Mythic,
        prerequisites: &["belief_engine"],
        unlocks: &["world_shaping"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "world_shaping",
        era: Era::Demiurge,
        prerequisites: &["living_legends"],
        unlocks: &["genesis_forge"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "genesis_forge",
        era: Era::Demiurge,
        prerequisites: &["world_shaping"],
        unlocks: &["first_law"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "first_law",
        era: Era::Demiurge,
        prerequisites: &["genesis_forge"],
        unlocks: &["godhood_rites"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "godhood_rites",
        era: Era::Pantheon,
        prerequisites: &["first_law"],
        unlocks: &["divine_council"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "divine_council",
        era: Era::Pantheon,
        prerequisites: &["godhood_rites"],
        unlocks: &["sacred_mathematics"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "sacred_mathematics",
        era: Era::Pantheon,
        prerequisites: &["divine_council"],
        unlocks: &["omega_point"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "omega_point",
        era: Era::Omega,
        prerequisites: &["sacred_mathematics"],
        unlocks: &["final_theory"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "final_theory",
        era: Era::Omega,
        prerequisites: &["omega_point"],
        unlocks: &["closing_loop"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "closing_loop",
        era: Era::Omega,
        prerequisites: &["final_theory"],
        unlocks: &["new_big_bang"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "new_big_bang",
        era: Era::Rebirth,
        prerequisites: &["closing_loop"],
        unlocks: &["seed_universe"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "seed_universe",
        era: Era::Rebirth,
        prerequisites: &["new_big_bang"],
        unlocks: &["the_next_box"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "the_next_box",
        era: Era::Rebirth,
        prerequisites: &["seed_universe"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
];
