//! Discoveries from the medieval age through the information age.

use super::*;

pub(super) const HISTORIC: &[TechNode] = &[
    TechNode {
        name: "feudalism",
        era: Era::Medieval,
        prerequisites: &["law_code"],
        unlocks: &["heraldry"],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "heraldry",
        era: Era::Medieval,
        prerequisites: &["feudalism"],
        unlocks: &[],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "plate_armor",
        era: Era::Medieval,
        prerequisites: &["ironworking"],
        unlocks: &[],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "longbow",
        era: Era::Medieval,
        prerequisites: &["hunting"],
        unlocks: &[],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "windmill",
        era: Era::Medieval,
        prerequisites: &["engineering"],
        unlocks: &["mill"],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "watermill",
        era: Era::Medieval,
        prerequisites: &["engineering"],
        unlocks: &["mill"],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "mill",
        era: Era::Medieval,
        prerequisites: &["windmill"],
        unlocks: &[],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "plow",
        era: Era::Medieval,
        prerequisites: &["plowing", "ironworking"],
        unlocks: &[],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "paper",
        era: Era::Medieval,
        prerequisites: &["writing"],
        unlocks: &["printing"],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "university_concept",
        era: Era::Medieval,
        prerequisites: &["library_concept"],
        unlocks: &[],
        discovery_rate: 0.8,
    },
    TechNode {
        name: "gothic_architecture",
        era: Era::Medieval,
        prerequisites: &["arch", "engineering"],
        unlocks: &[],
        discovery_rate: 0.8,
    },
    TechNode {
        name: "alchemy",
        era: Era::Medieval,
        prerequisites: &["chemistry"],
        unlocks: &["scientific_method"],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "magnetic_compass",
        era: Era::Medieval,
        prerequisites: &["navigation"],
        unlocks: &["exploration"],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "gunpowder",
        era: Era::Medieval,
        prerequisites: &["alchemy"],
        unlocks: &["dynamite"],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "printing",
        era: Era::Renaissance,
        prerequisites: &["paper"],
        unlocks: &[],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "telescope",
        era: Era::Renaissance,
        prerequisites: &["glass"],
        unlocks: &["astronomy_helio"],
        discovery_rate: 0.8,
    },
    TechNode {
        name: "microscope",
        era: Era::Renaissance,
        prerequisites: &["glass"],
        unlocks: &["germ_theory"],
        discovery_rate: 0.8,
    },
    TechNode {
        name: "perspective_drawing",
        era: Era::Renaissance,
        prerequisites: &["geometry"],
        unlocks: &["oil_painting"],
        discovery_rate: 0.8,
    },
    TechNode {
        name: "double_entry_bookkeeping",
        era: Era::Renaissance,
        prerequisites: &["currency"],
        unlocks: &[],
        discovery_rate: 0.8,
    },
    TechNode {
        name: "oil_painting",
        era: Era::Renaissance,
        prerequisites: &["perspective_drawing"],
        unlocks: &[],
        discovery_rate: 0.7,
    },
    TechNode {
        name: "opera",
        era: Era::Renaissance,
        prerequisites: &["theater"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "scientific_method",
        era: Era::Renaissance,
        prerequisites: &["alchemy", "philosophy"],
        unlocks: &[],
        discovery_rate: 0.9,
    },
    TechNode {
        name: "anatomy_modern",
        era: Era::Renaissance,
        prerequisites: &["anatomy"],
        unlocks: &[],
        discovery_rate: 0.7,
    },
    TechNode {
        name: "cartography",
        era: Era::Renaissance,
        prerequisites: &["navigation"],
        unlocks: &["exploration"],
        discovery_rate: 0.8,
    },
    TechNode {
        name: "exploration",
        era: Era::Renaissance,
        prerequisites: &["cartography", "magnetic_compass"],
        unlocks: &[],
        discovery_rate: 0.8,
    },
    TechNode {
        name: "astronomy_helio",
        era: Era::Renaissance,
        prerequisites: &["telescope"],
        unlocks: &[],
        discovery_rate: 0.7,
    },
    TechNode {
        name: "steam_engine",
        era: Era::Industrial,
        prerequisites: &["scientific_method"],
        unlocks: &["railroad", "factory"],
        discovery_rate: 1.6,
    },
    TechNode {
        name: "railroad",
        era: Era::Industrial,
        prerequisites: &["steam_engine"],
        unlocks: &[],
        discovery_rate: 1.6,
    },
    TechNode {
        name: "factory",
        era: Era::Industrial,
        prerequisites: &["steam_engine"],
        unlocks: &["sewing_machine"],
        discovery_rate: 1.6,
    },
    TechNode {
        name: "telegraph",
        era: Era::Industrial,
        prerequisites: &["electricity_generation"],
        unlocks: &["telephone"],
        discovery_rate: 1.4,
    },
    TechNode {
        name: "photography",
        era: Era::Industrial,
        prerequisites: &["chemistry"],
        unlocks: &["motion_picture"],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "internal_combustion",
        era: Era::Industrial,
        prerequisites: &["steam_engine"],
        unlocks: &["automobile", "airplane"],
        discovery_rate: 1.4,
    },
    TechNode {
        name: "electricity_generation",
        era: Era::Industrial,
        prerequisites: &["scientific_method"],
        unlocks: &["telegraph", "telephone"],
        discovery_rate: 1.6,
    },
    TechNode {
        name: "electricity",
        era: Era::Industrial,
        prerequisites: &["electricity_generation"],
        unlocks: &[],
        discovery_rate: 1.6,
    },
    TechNode {
        name: "vaccine",
        era: Era::Industrial,
        prerequisites: &["germ_theory"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "anesthesia",
        era: Era::Industrial,
        prerequisites: &["surgery", "chemistry"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "germ_theory",
        era: Era::Industrial,
        prerequisites: &["microscope"],
        unlocks: &["antibiotics"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "dynamite",
        era: Era::Industrial,
        prerequisites: &["gunpowder", "chemistry"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "sewer",
        era: Era::Industrial,
        prerequisites: &["plumbing", "germ_theory"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "sewing_machine",
        era: Era::Industrial,
        prerequisites: &["factory"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "bicycle",
        era: Era::Industrial,
        prerequisites: &["factory"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "telephone",
        era: Era::Modern,
        prerequisites: &["telegraph"],
        unlocks: &[],
        discovery_rate: 1.4,
    },
    TechNode {
        name: "radio",
        era: Era::Modern,
        prerequisites: &["electricity_generation"],
        unlocks: &["television"],
        discovery_rate: 1.4,
    },
    TechNode {
        name: "automobile",
        era: Era::Modern,
        prerequisites: &["internal_combustion"],
        unlocks: &[],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "airplane",
        era: Era::Modern,
        prerequisites: &["internal_combustion"],
        unlocks: &["jet_engine"],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "motion_picture",
        era: Era::Modern,
        prerequisites: &["photography"],
        unlocks: &[],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "antibiotics",
        era: Era::Modern,
        prerequisites: &["germ_theory"],
        unlocks: &[],
        discovery_rate: 1.4,
    },
    TechNode {
        name: "plastic",
        era: Era::Modern,
        prerequisites: &["chemistry"],
        unlocks: &[],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "refrigeration",
        era: Era::Modern,
        prerequisites: &["electricity"],
        unlocks: &[],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "nuclear_fission",
        era: Era::Modern,
        prerequisites: &["physics", "scientific_method"],
        unlocks: &[],
        discovery_rate: 0.8,
    },
    TechNode {
        name: "computer_concept",
        era: Era::Modern,
        prerequisites: &["mathematics", "electricity"],
        unlocks: &["computer"],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "television",
        era: Era::Modern,
        prerequisites: &["radio"],
        unlocks: &[],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "jet_engine",
        era: Era::Modern,
        prerequisites: &["airplane"],
        unlocks: &[],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "computer",
        era: Era::Information,
        prerequisites: &["computer_concept"],
        unlocks: &["internet", "AI"],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "internet",
        era: Era::Information,
        prerequisites: &["computer", "telephone"],
        unlocks: &["social_media"],
        discovery_rate: 1.2,
    },
    TechNode {
        name: "satellite",
        era: Era::Information,
        prerequisites: &["jet_engine", "radio"],
        unlocks: &["GPS"],
        discovery_rate: 1.0,
    },
    TechNode {
        name: "smartphone",
        era: Era::Information,
        prerequisites: &["computer", "telephone"],
        unlocks: &[],
        discovery_rate: 0.4,
    },
    TechNode {
        name: "gene_editing",
        era: Era::Information,
        prerequisites: &["anatomy_modern", "computer"],
        unlocks: &[],
        discovery_rate: 0.3,
    },
    TechNode {
        name: "AI",
        era: Era::Information,
        prerequisites: &["computer"],
        unlocks: &[],
        discovery_rate: 0.3,
    },
    TechNode {
        name: "GPS",
        era: Era::Information,
        prerequisites: &["satellite"],
        unlocks: &[],
        discovery_rate: 0.4,
    },
    TechNode {
        name: "social_media",
        era: Era::Information,
        prerequisites: &["internet"],
        unlocks: &[],
        discovery_rate: 0.4,
    },
    TechNode {
        name: "renewable_energy",
        era: Era::Information,
        prerequisites: &["electricity_generation"],
        unlocks: &[],
        discovery_rate: 0.4,
    },
];
