//! Discoveries from the atomic age through the posthuman age.

use super::*;

pub(super) const NEAR_FUTURE: &[TechNode] = &[
    TechNode {
        name: "rocketry",
        era: Era::Atomic,
        prerequisites: &["internal_combustion", "chemistry"],
        unlocks: &["spaceflight"],
        discovery_rate: 0.4,
    },
    TechNode {
        name: "telescopes",
        era: Era::Atomic,
        prerequisites: &["telescope", "satellite"],
        unlocks: &[],
        discovery_rate: 0.4,
    },
    TechNode {
        name: "spaceflight",
        era: Era::Space,
        prerequisites: &["rocketry", "satellite"],
        unlocks: &["satellite_network"],
        discovery_rate: 0.35,
    },
    TechNode {
        name: "satellite_network",
        era: Era::Space,
        prerequisites: &["spaceflight"],
        unlocks: &[],
        discovery_rate: 0.35,
    },
    TechNode {
        name: "microchip",
        era: Era::Digital,
        prerequisites: &["computer", "AI"],
        unlocks: &["mobile", "cloud"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "mobile",
        era: Era::Digital,
        prerequisites: &["smartphone", "microchip"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "cloud",
        era: Era::Digital,
        prerequisites: &["internet", "microchip"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "quantum_compute",
        era: Era::Quantum,
        prerequisites: &["microchip", "physics"],
        unlocks: &["crypto", "entanglement"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "crypto",
        era: Era::Quantum,
        prerequisites: &["quantum_compute"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "entanglement",
        era: Era::Quantum,
        prerequisites: &["quantum_compute"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "solar_grid",
        era: Era::Solar,
        prerequisites: &["renewable_energy"],
        unlocks: &["battery_grid"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "battery_grid",
        era: Era::Solar,
        prerequisites: &["solar_grid"],
        unlocks: &["smart_grid"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "smart_grid",
        era: Era::Solar,
        prerequisites: &["battery_grid", "AI"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "tokamak",
        era: Era::Fusion,
        prerequisites: &["nuclear_fission", "smart_grid"],
        unlocks: &["fusion_reactor"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "fusion_reactor",
        era: Era::Fusion,
        prerequisites: &["tokamak"],
        unlocks: &["helium3"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "helium3",
        era: Era::Fusion,
        prerequisites: &["fusion_reactor", "spaceflight"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "biotech",
        era: Era::Genetic,
        prerequisites: &["gene_editing"],
        unlocks: &["genome_edit"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "genome_edit",
        era: Era::Genetic,
        prerequisites: &["biotech"],
        unlocks: &["cloning"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "cloning",
        era: Era::Genetic,
        prerequisites: &["genome_edit"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "space_elevator",
        era: Era::Orbital,
        prerequisites: &["spaceflight", "fusion_reactor"],
        unlocks: &["orbital_ring"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "orbital_ring",
        era: Era::Orbital,
        prerequisites: &["space_elevator"],
        unlocks: &["orbital_factory"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "orbital_factory",
        era: Era::Orbital,
        prerequisites: &["orbital_ring"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "moon_base",
        era: Era::Lunar,
        prerequisites: &["space_elevator"],
        unlocks: &["lunar_mining"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "lunar_mining",
        era: Era::Lunar,
        prerequisites: &["moon_base"],
        unlocks: &["low_gravity"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "low_gravity",
        era: Era::Lunar,
        prerequisites: &["moon_base"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "interplanetary",
        era: Era::Martian,
        prerequisites: &["moon_base"],
        unlocks: &["mars_colony"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "mars_colony",
        era: Era::Martian,
        prerequisites: &["interplanetary"],
        unlocks: &["terraforming"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "terraforming",
        era: Era::Martian,
        prerequisites: &["mars_colony", "biotech"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "cybernetics",
        era: Era::Cyber,
        prerequisites: &["anatomy_modern", "microchip"],
        unlocks: &["augmentation"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "neural_interface",
        era: Era::Cyber,
        prerequisites: &["cybernetics", "AI"],
        unlocks: &["brain_upload"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "augmentation",
        era: Era::Cyber,
        prerequisites: &["cybernetics"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "brain_upload",
        era: Era::Neural,
        prerequisites: &["neural_interface"],
        unlocks: &["synthetic_mind"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "synthetic_mind",
        era: Era::Neural,
        prerequisites: &["brain_upload", "AI"],
        unlocks: &["consciousness_net"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "consciousness_net",
        era: Era::Neural,
        prerequisites: &["synthetic_mind"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "longevity",
        era: Era::Posthuman,
        prerequisites: &["genome_edit"],
        unlocks: &["synthetic_body"],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "synthetic_body",
        era: Era::Posthuman,
        prerequisites: &["longevity", "cybernetics"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
    TechNode {
        name: "post_scarcity",
        era: Era::Posthuman,
        prerequisites: &["fusion_reactor", "AI"],
        unlocks: &[],
        discovery_rate: 0.6,
    },
];
